import { stripMarkdownExtension, upsertObsidianSystemDocument } from './authoring';
import { buildKnowledgeCatalogCoverageAsync, loadKnowledgeBackfillCatalog } from './obsidianCatalogService';
import { LINT_PATH } from './obsidianPathUtils';
import { getLatestObsidianGraphAuditSnapshot } from './obsidianQualityService';
import { getObsidianAdapterRuntimeStatus } from './router';
import { getObsidianVaultRuntimeInfo } from '../../utils/obsidianEnv';
import type {
  ObsidianKnowledgeCompilationStats,
  ObsidianSemanticLintAuditIssue,
  ObsidianSemanticLintAuditResult,
  ObsidianSemanticLintPersistenceResult,
} from './knowledgeCompilerService';

const SEMANTIC_LINT_NEGATIVE_KNOWLEDGE_ROOT = 'ops/improvement/negative-knowledge/semantic-lint';
const SEMANTIC_LINT_CURRENT_PATH = `${SEMANTIC_LINT_NEGATIVE_KNOWLEDGE_ROOT}/CURRENT.md`;

const toText = (value: unknown): string => String(value || '').trim();

const toSlug = (value: string): string => {
  return String(value || '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80) || 'change';
};

const dedupeStrings = (values: Array<string | null | undefined>): string[] => {
  const seen = new Set<string>();
  const result: string[] = [];
  for (const value of values) {
    const normalized = String(value || '').trim();
    if (!normalized || seen.has(normalized)) {
      continue;
    }
    seen.add(normalized);
    result.push(normalized);
  }
  return result;
};

const clampInt = (value: unknown, fallback: number, min: number, max: number): number => {
  const parsed = Number.parseInt(String(value ?? ''), 10);
  if (!Number.isFinite(parsed)) {
    return fallback;
  }
  return Math.min(max, Math.max(min, parsed));
};

const readRemoteVaultRuntime = (adapterRuntime: Record<string, unknown> | null | undefined): Record<string, unknown> | null => {
  const remoteMcp = adapterRuntime?.remoteMcp;
  if (!remoteMcp || typeof remoteMcp !== 'object') {
    return null;
  }

  const remoteAdapterRuntime = (remoteMcp as Record<string, unknown>).remoteAdapterRuntime;
  if (!remoteAdapterRuntime || typeof remoteAdapterRuntime !== 'object') {
    return null;
  }

  const vaultRuntime = (remoteAdapterRuntime as Record<string, unknown>).vaultRuntime;
  if (!vaultRuntime || typeof vaultRuntime !== 'object') {
    return null;
  }

  return vaultRuntime as Record<string, unknown>;
};

const buildSemanticLintSummary = (issues: ObsidianSemanticLintAuditIssue[]): string => {
  if (issues.length === 0) {
    return 'No semantic lint issues detected across compiler lint, graph quality, shared coverage, or runtime-vs-doc alignment.';
  }
  return `Detected ${issues.length} semantic lint issues across compiler lint, graph quality, shared coverage, or runtime-vs-doc alignment.`;
};

const buildSemanticLintIssueTargetPath = (issue: ObsidianSemanticLintAuditIssue): string => {
  return `${SEMANTIC_LINT_NEGATIVE_KNOWLEDGE_ROOT}/issues/${issue.kind}-${toSlug(`${issue.id}-${issue.message}`)}.md`;
};

const buildSemanticLintIssueContent = (params: {
  generatedAt: string;
  issue: ObsidianSemanticLintAuditIssue;
  summaryPath: string;
}): string => {
  const title = `${params.issue.kind}: ${params.issue.message}`.slice(0, 160);
  return [
    `# ${title}`,
    '',
    '## Classification',
    `- Kind: ${params.issue.kind}`,
    `- Severity: ${params.issue.severity}`,
    `- Observed At: ${params.generatedAt}`,
    '',
    '## Observation',
    params.issue.message,
    '',
    '## Evidence',
    ...(params.issue.evidenceRefs.length > 0
      ? params.issue.evidenceRefs.map((value) => `- ${value}`)
      : ['- No explicit evidence refs captured.']),
    '',
    '## Suggested Next Step',
    `- ${params.issue.suggestedNextStep}`,
    '',
    '## Control Plane Backlinks',
    `- Current summary: ${params.summaryPath}`,
    '- Generated by: semantic.lint.audit',
  ].join('\n');
};

const buildSemanticLintCurrentContent = (params: {
  generatedAt: string;
  summary: string;
  issues: ObsidianSemanticLintAuditIssue[];
  followUps: string[];
  coverage: ObsidianSemanticLintAuditResult['coverage'];
  issuePaths: string[];
}): string => {
  const openIssueLines = params.issues.length > 0
    ? params.issues.map((issue, index) => {
      const issuePath = params.issuePaths[index] || 'unwritten';
      return [`- [${issue.severity}] ${issue.kind}: ${issue.message}`, `  - Object: ${issuePath}`, `  - Next: ${issue.suggestedNextStep}`].join('\n');
    })
    : ['- No open semantic lint issues.'];

  return [
    '# Semantic Lint Current State',
    '',
    params.summary,
    '',
    '## Snapshot',
    `- Generated At: ${params.generatedAt}`,
    `- Healthy: ${String(params.issues.length === 0)}`,
    `- Issue Count: ${params.issues.length}`,
    `- Coverage: ${params.coverage.presentEntries}/${params.coverage.totalEntries} visible in shared vault`,
    '',
    '## Open Issues',
    ...openIssueLines,
    '',
    '## Follow Ups',
    ...(params.followUps.length > 0 ? params.followUps.map((value) => `- ${value}`) : ['- No explicit follow-ups.']),
  ].join('\n');
};

const persistSemanticLintAuditResult = async (params: {
  generatedAt: string;
  summary: string;
  issues: ObsidianSemanticLintAuditIssue[];
  followUps: string[];
  coverage: ObsidianSemanticLintAuditResult['coverage'];
}): Promise<ObsidianSemanticLintPersistenceResult> => {
  const issuePaths = params.issues.map((issue) => buildSemanticLintIssueTargetPath(issue));
  const vaultRuntime = getObsidianVaultRuntimeInfo();
  const vaultPath = vaultRuntime.configured && vaultRuntime.exists ? vaultRuntime.root : '';
  if (!vaultPath) {
    return {
      attempted: false,
      summaryPath: SEMANTIC_LINT_CURRENT_PATH,
      issuePaths,
      writtenArtifacts: [],
      skippedReasons: ['shared vault is not configured or not visible'],
    };
  }

  const writtenArtifacts: string[] = [];
  const skippedReasons: string[] = [];

  for (const issue of params.issues) {
    const issuePath = buildSemanticLintIssueTargetPath(issue);
    const writeResult = await upsertObsidianSystemDocument({
      vaultPath,
      fileName: stripMarkdownExtension(issuePath),
      content: buildSemanticLintIssueContent({
        generatedAt: params.generatedAt,
        issue,
        summaryPath: SEMANTIC_LINT_CURRENT_PATH,
      }),
      tags: ['semantic-lint', 'negative-knowledge', issue.kind, issue.severity],
      allowHighLinkDensity: true,
      skipKnowledgeCompilation: true,
      properties: {
        title: `${issue.kind}: ${issue.message}`.slice(0, 160),
        source_kind: 'semantic-lint-issue',
        generated_by: 'semantic.lint.audit',
        canonical_key: `semantic-lint/${issue.kind}/${toSlug(issue.id || issue.message)}`,
        issue_kind: issue.kind,
        severity: issue.severity,
        observed_at: params.generatedAt,
      },
    });

    if (writeResult.ok && writeResult.path) {
      writtenArtifacts.push(writeResult.path);
      continue;
    }

    skippedReasons.push(`failed to write ${issuePath}`);
  }

  const summaryWrite = await upsertObsidianSystemDocument({
    vaultPath,
    fileName: stripMarkdownExtension(SEMANTIC_LINT_CURRENT_PATH),
    content: buildSemanticLintCurrentContent({
      generatedAt: params.generatedAt,
      summary: params.summary,
      issues: params.issues,
      followUps: params.followUps,
      coverage: params.coverage,
      issuePaths,
    }),
    tags: ['semantic-lint', 'negative-knowledge', 'current'],
    allowHighLinkDensity: true,
    skipKnowledgeCompilation: true,
    properties: {
      title: 'Semantic Lint Current State',
      source_kind: 'semantic-lint-current',
      generated_by: 'semantic.lint.audit',
      canonical_key: 'semantic-lint/current',
      issue_count: params.issues.length,
      observed_at: params.generatedAt,
      healthy: params.issues.length === 0,
    },
  });

  if (summaryWrite.ok && summaryWrite.path) {
    writtenArtifacts.push(summaryWrite.path);
  } else {
    skippedReasons.push(`failed to write ${SEMANTIC_LINT_CURRENT_PATH}`);
  }

  return {
    attempted: true,
    summaryPath: SEMANTIC_LINT_CURRENT_PATH,
    issuePaths,
    writtenArtifacts,
    skippedReasons,
  };
};

const dedupeSemanticLintIssues = (issues: ObsidianSemanticLintAuditIssue[]): ObsidianSemanticLintAuditIssue[] => {
  const seen = new Set<string>();
  const result: ObsidianSemanticLintAuditIssue[] = [];
  for (const issue of issues) {
    const key = `${issue.kind}:${issue.message}`;
    if (seen.has(key)) {
      continue;
    }
    seen.add(key);
    result.push(issue);
  }
  return result;
};

export const runSemanticLintAudit = async (params: {
  maxIssues?: number;
  includeGraphAudit?: boolean;
  persistFindings?: boolean;
}, deps: {
  getCompilationStats: () => ObsidianKnowledgeCompilationStats;
}): Promise<ObsidianSemanticLintAuditResult> => {
  const maxIssues = clampInt(params.maxIssues, 12, 1, 30);
  const issues: ObsidianSemanticLintAuditIssue[] = [];
  const compiler = deps.getCompilationStats();
  const coverage = await buildKnowledgeCatalogCoverageAsync(loadKnowledgeBackfillCatalog().entries);
  const graphAudit = params.includeGraphAudit === false
    ? null
    : await getLatestObsidianGraphAuditSnapshot().catch(() => null);
  const localVault = getObsidianVaultRuntimeInfo();
  const adapterRuntime = getObsidianAdapterRuntimeStatus() as Record<string, unknown>;

  for (const issue of compiler.lastLintSummary?.issues || []) {
    issues.push({
      id: `compiler-${issue.kind}-${toSlug(issue.message)}`,
      kind: 'compiler-lint',
      severity: issue.kind === 'canonical_collision' || issue.kind === 'invalid_lifecycle' ? 'medium' : 'low',
      message: issue.message,
      evidenceRefs: issue.filePaths,
      suggestedNextStep: 'Refresh the corresponding knowledge-control artifact and source refs so the semantic owner remains current.',
    });
  }

  if (coverage.missingEntries > 0) {
    issues.push({
      id: 'coverage-missing-shared-targets',
      kind: 'coverage-gap',
      severity: coverage.operatorPrimaryMissing > 0 || coverage.startHereMissing > 0 ? 'high' : 'medium',
      message: `${coverage.missingEntries} shared wiki targets are still missing from the verified shared-vault view.`,
      evidenceRefs: coverage.missingTargetPaths.slice(0, 6),
      suggestedNextStep: 'Backfill missing shared wiki targets before treating repo mirrors as canonical.',
    });
  }

  if (graphAudit) {
    if (graphAudit.totals.unresolvedLinks > 0) {
      issues.push({
        id: 'graph-unresolved-links',
        kind: 'graph-quality',
        severity: graphAudit.totals.unresolvedLinks > graphAudit.thresholds.unresolvedLinks ? 'high' : 'medium',
        message: `${graphAudit.totals.unresolvedLinks} unresolved links are present in the shared graph.`,
        evidenceRefs: [LINT_PATH],
        suggestedNextStep: 'Resolve or retarget unresolved links so object pages stay traversable.',
      });
    }
    if (graphAudit.totals.orphanFiles > 0) {
      issues.push({
        id: 'graph-orphan-files',
        kind: 'graph-quality',
        severity: graphAudit.totals.orphanFiles > graphAudit.thresholds.orphanFiles ? 'high' : 'medium',
        message: `${graphAudit.totals.orphanFiles} orphan files are disconnected from the current semantic graph.`,
        evidenceRefs: [LINT_PATH],
        suggestedNextStep: 'Add backlinks or hub references so active objects do not become dead ends.',
      });
    }
    if (graphAudit.totals.missingRequiredPropertyFiles > 0) {
      issues.push({
        id: 'graph-missing-required-properties',
        kind: 'graph-quality',
        severity: 'medium',
        message: `${graphAudit.totals.missingRequiredPropertyFiles} files are missing required metadata properties.`,
        evidenceRefs: [LINT_PATH],
        suggestedNextStep: 'Normalize frontmatter so canonical key, freshness, and provenance remain machine-readable.',
      });
    }
  }

  const selectedByCapability = adapterRuntime.selectedByCapability as Record<string, unknown> | undefined;
  const remoteSelectedForWrite = selectedByCapability?.write_note === 'remote-mcp';
  const remoteVaultRuntime = readRemoteVaultRuntime(adapterRuntime);
  if (remoteSelectedForWrite && !remoteVaultRuntime) {
    issues.push({
      id: 'runtime-remote-vault-missing',
      kind: 'runtime-doc-mismatch',
      severity: 'high',
      message: 'remote-mcp is selected for writes but remote vault runtime details are unavailable.',
      evidenceRefs: ['obsidian.adapter.status'],
      suggestedNextStep: 'Re-probe the shared MCP adapter and verify remote vault parity before trusting write success.',
    });
  }
  if (remoteSelectedForWrite && remoteVaultRuntime) {
    const localName = toText(localVault.resolvedName);
    const remoteName = toText(remoteVaultRuntime.resolvedName);
    const localDesktop = Boolean(localVault.looksLikeDesktopVault);
    const remoteDesktop = Boolean(remoteVaultRuntime.looksLikeDesktopVault);
    const sharedTopLevel = ['chat', 'guilds', 'ops'].filter((dir) =>
      (localVault.topLevelDirectories || []).includes(dir)
      && Array.isArray(remoteVaultRuntime.topLevelDirectories)
      && remoteVaultRuntime.topLevelDirectories.includes(dir),
    );
    if ((localName && remoteName && localName !== remoteName) || !localDesktop || !remoteDesktop || sharedTopLevel.length < 3) {
      issues.push({
        id: 'runtime-vault-parity-mismatch',
        kind: 'runtime-doc-mismatch',
        severity: 'high',
        message: 'Shared write routing is active but local and remote vault shapes are not fully aligned.',
        evidenceRefs: ['obsidian.adapter.status', 'operator.snapshot'],
        suggestedNextStep: 'Align remote vault shape and resolved vault identity before relying on semantic owner writes.',
      });
    }
  }

  const uniqueIssues = dedupeSemanticLintIssues(issues).slice(0, maxIssues);
  const summary = buildSemanticLintSummary(uniqueIssues);
  const followUps = dedupeStrings(uniqueIssues.map((issue) => issue.suggestedNextStep));
  const coverageSummary = {
    totalEntries: coverage.totalEntries,
    presentEntries: coverage.presentEntries,
    missingEntries: coverage.missingEntries,
  };
  const persistence = params.persistFindings === false
    ? undefined
    : await persistSemanticLintAuditResult({
      generatedAt: new Date().toISOString(),
      summary,
      issues: uniqueIssues,
      followUps,
      coverage: coverageSummary,
    });

  return {
    summary,
    healthy: uniqueIssues.length === 0,
    issueCount: uniqueIssues.length,
    issues: uniqueIssues,
    followUps,
    coverage: coverageSummary,
    persistence,
  };
};