FROM docker.litellm.ai/berriai/litellm-database:main-stable

WORKDIR /app

COPY litellm.config.yaml /app/litellm.config.yaml

EXPOSE 4000

CMD ["--config", "/app/litellm.config.yaml", "--host", "0.0.0.0", "--port", "4000"]
