module.exports = {
  apps: [
    {
      name: 'muel-local-orchestrator-worker',
      script: 'node',
      args: '--import tsx scripts/agent-role-worker.ts --role=local-orchestrator',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      time: true,
      env: {
        NODE_ENV: 'production',
        AGENT_ROLE_WORKER_ROLE: 'local-orchestrator',
        AGENT_ROLE_WORKER_PORT: '8790',
      },
    },
    {
      name: 'muel-opendev-worker',
      script: 'node',
      args: '--import tsx scripts/agent-role-worker.ts --role=opendev',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      time: true,
      env: {
        NODE_ENV: 'production',
        AGENT_ROLE_WORKER_ROLE: 'opendev',
        AGENT_ROLE_WORKER_PORT: '8791',
      },
    },
    {
      name: 'muel-nemoclaw-worker',
      script: 'node',
      args: '--import tsx scripts/agent-role-worker.ts --role=nemoclaw',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      time: true,
      env: {
        NODE_ENV: 'production',
        AGENT_ROLE_WORKER_ROLE: 'nemoclaw',
        AGENT_ROLE_WORKER_PORT: '8792',
      },
    },
    {
      name: 'muel-openjarvis-worker',
      script: 'node',
      args: '--import tsx scripts/agent-role-worker.ts --role=openjarvis',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      time: true,
      env: {
        NODE_ENV: 'production',
        AGENT_ROLE_WORKER_ROLE: 'openjarvis',
        AGENT_ROLE_WORKER_PORT: '8793',
      },
    },
  ],
};