import { AGENT_MAX_SESSION_HISTORY } from '../config';

export const MULTI_AGENT_MAX_SESSION_HISTORY = AGENT_MAX_SESSION_HISTORY;
export const MULTI_AGENT_SESSION_OUTCOME_CACHE_SIZE = 200;
export const MULTI_AGENT_SESSION_OUTCOME_TTL_MS = 120_000;
export const MULTI_AGENT_SESSION_OUTCOME_MAX_PER_GUILD = 5;