-- Migration: agent_weekly_reports for supabase-first decision snapshots
-- Apply in Supabase SQL Editor (idempotent)

create table if not exists public.agent_weekly_reports (
  id bigint generated by default as identity primary key,
  report_key text not null unique,
  report_kind text not null,
  guild_id text,
  provider text,
  action_prefix text,
  baseline_from timestamptz,
  baseline_to timestamptz,
  candidate_from timestamptz,
  candidate_to timestamptz,
  baseline_summary jsonb not null default '{}'::jsonb,
  candidate_summary jsonb not null default '{}'::jsonb,
  delta_summary jsonb not null default '{}'::jsonb,
  top_actions jsonb not null default '{}'::jsonb,
  markdown text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (report_kind in ('llm_latency_weekly', 'go_no_go_weekly', 'hybrid_weekly', 'rollback_rehearsal_weekly', 'memory_queue_weekly', 'self_improvement_patterns', 'jarvis_optimize_result', 'cross_loop_origin', 'convergence_report'))
);

do $$
begin
  if exists (
    select 1
    from pg_constraint c
    join pg_class t on t.oid = c.conrelid
    join pg_namespace n on n.oid = t.relnamespace
    where n.nspname = 'public'
      and t.relname = 'agent_weekly_reports'
      and c.conname = 'agent_weekly_reports_report_kind_check'
  ) then
    alter table public.agent_weekly_reports
      drop constraint agent_weekly_reports_report_kind_check;
  end if;

  alter table public.agent_weekly_reports
    add constraint agent_weekly_reports_report_kind_check
    check (
      report_kind in (
        'llm_latency_weekly',
        'go_no_go_weekly',
        'hybrid_weekly',
        'rollback_rehearsal_weekly',
        'memory_queue_weekly',
        'self_improvement_patterns',
        'jarvis_optimize_result',
        'cross_loop_origin',
        'convergence_report'
      )
    );
end $$;

create index if not exists idx_agent_weekly_reports_kind_created
  on public.agent_weekly_reports (report_kind, created_at desc);

create index if not exists idx_agent_weekly_reports_guild_created
  on public.agent_weekly_reports (guild_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_agent_weekly_reports_updated_at on public.agent_weekly_reports;
create trigger trg_agent_weekly_reports_updated_at
before update on public.agent_weekly_reports
for each row
execute function public.set_updated_at();

alter table public.agent_weekly_reports enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'agent_weekly_reports'
      and policyname = 'agent_weekly_reports_guild_all'
  ) then
    create policy agent_weekly_reports_guild_all on public.agent_weekly_reports
      for all
      using (auth.role() = 'service_role' or coalesce(guild_id, '') = coalesce(auth.jwt() ->> 'guild_id', ''))
      with check (auth.role() = 'service_role' or coalesce(guild_id, '') = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;
end $$;

-- Workflow state persistence (OpenJarvis unattended)
create table if not exists public.workflow_sessions (
  id bigint generated by default as identity primary key,
  session_id text not null unique,
  workflow_name text not null,
  stage text not null,
  scope text,
  status text not null,
  metadata jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (status in ('proposed', 'classified', 'routed', 'executing', 'verifying', 'approving', 'released', 'recovering', 'failed'))
);

create table if not exists public.workflow_steps (
  id bigint generated by default as identity primary key,
  session_id text not null references public.workflow_sessions(session_id) on delete cascade,
  step_order integer not null,
  step_name text not null,
  agent_role text,
  status text not null,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  duration_ms integer,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (status in ('queued', 'running', 'passed', 'failed', 'skipped'))
);

create unique index if not exists idx_workflow_steps_session_order
  on public.workflow_steps (session_id, step_order);

create table if not exists public.workflow_events (
  id bigint generated by default as identity primary key,
  session_id text not null references public.workflow_sessions(session_id) on delete cascade,
  event_type text not null,
  from_state text,
  to_state text,
  handoff_from text,
  handoff_to text,
  decision_reason text,
  evidence_id text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_workflow_sessions_status_started
  on public.workflow_sessions (status, started_at desc);

create index if not exists idx_workflow_steps_session_status
  on public.workflow_steps (session_id, status);

create index if not exists idx_workflow_events_session_created
  on public.workflow_events (session_id, created_at desc);

drop trigger if exists trg_workflow_sessions_updated_at on public.workflow_sessions;
create trigger trg_workflow_sessions_updated_at
before update on public.workflow_sessions
for each row
execute function public.set_updated_at();

drop trigger if exists trg_workflow_steps_updated_at on public.workflow_steps;
create trigger trg_workflow_steps_updated_at
before update on public.workflow_steps
for each row
execute function public.set_updated_at();
