-- Migration: agent_weekly_reports for supabase-first decision snapshots
-- Apply in Supabase SQL Editor (idempotent)

create table if not exists public.agent_weekly_reports (
  id bigint generated by default as identity primary key,
  report_key text not null unique,
  report_kind text not null,
  guild_id text,
  provider text,
  action_prefix text,
  baseline_from timestamptz,
  baseline_to timestamptz,
  candidate_from timestamptz,
  candidate_to timestamptz,
  baseline_summary jsonb not null default '{}'::jsonb,
  candidate_summary jsonb not null default '{}'::jsonb,
  delta_summary jsonb not null default '{}'::jsonb,
  top_actions jsonb not null default '{}'::jsonb,
  markdown text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (report_kind in ('llm_latency_weekly', 'go_no_go_weekly', 'hybrid_weekly'))
);

create index if not exists idx_agent_weekly_reports_kind_created
  on public.agent_weekly_reports (report_kind, created_at desc);

create index if not exists idx_agent_weekly_reports_guild_created
  on public.agent_weekly_reports (guild_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_agent_weekly_reports_updated_at on public.agent_weekly_reports;
create trigger trg_agent_weekly_reports_updated_at
before update on public.agent_weekly_reports
for each row
execute function public.set_updated_at();

alter table public.agent_weekly_reports enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'agent_weekly_reports'
      and policyname = 'agent_weekly_reports_guild_all'
  ) then
    create policy agent_weekly_reports_guild_all on public.agent_weekly_reports
      for all
      using (auth.role() = 'service_role' or coalesce(guild_id, '') = coalesce(auth.jwt() ->> 'guild_id', ''))
      with check (auth.role() = 'service_role' or coalesce(guild_id, '') = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;
end $$;
