/**
 * Security Pipeline Orchestrator
 *
 * Implements the Toss-style Discovery → Analysis two-phase pattern:
 *   1. Load security candidates (from JSONL generated by SAST scanner)
 *   2. Discovery phase: LLM filters candidates by vulnerability likelihood
 *   3. Analysis phase: LLM performs deep analysis on filtered candidates
 *
 * This module is consumed by cso.audit and security-audit skill actions.
 */

import { generateText, isAnyLlmConfigured } from '../llmClient';
import {
  listSecurityCandidates,
} from '../opencode/codeIndexService';
import type {
  MergedSecurityReviewUnit,
  DiscoveryResult,
  AnalysisVerdict,
} from '../securityCandidateContract';
import {
  normalizeDiscoveryResult,
  normalizeAnalysisVerdict,
} from '../securityCandidateContract';

// ──── Types ────────────────────────────────────────────────────────────────────

export type SecurityPipelineResult = {
  ok: boolean;
  totalCandidates: number;
  discoveryIncluded: number;
  discoveryExcluded: number;
  analysisVerdicts: AnalysisVerdict[];
  confirmedFindings: AnalysisVerdict[];
  summary: string;
  durationMs: number;
};

type DiscoveryBatch = {
  units: MergedSecurityReviewUnit[];
  batchIndex: number;
};

// ──── Config ───────────────────────────────────────────────────────────────────

const DISCOVERY_BATCH_SIZE = 15;
const ANALYSIS_BATCH_SIZE = 5;
const MAX_CANDIDATES_TO_PROCESS = 200;

// ──── Discovery Phase ──────────────────────────────────────────────────────────

const DISCOVERY_SYSTEM = [
  'You are a Discovery agent for security vulnerability analysis.',
  'Your role: quickly triage security candidates and decide which need deep analysis.',
  '',
  'GUIDELINES:',
  '1. Do NOT use external tools — judge solely from the provided code snippets.',
  '2. Be lenient: if there is ANY possibility of a vulnerability, include it.',
  '3. Only exclude candidates that are obviously safe (e.g., reading a constant, no user input flow).',
  '',
  'OUTPUT FORMAT: JSON matching DiscoveryResult schema:',
  '{',
  '  "analyze": [{ "unitId": "...", "disposition": "analyze", "priorityScore": 0-100, "shortReason": "...", "reasonCodes": ["XSS", "SQLI", ...] }],',
  '  "hold": [...],',
  '  "drop": [...]',
  '}',
  '',
  'Dispositions:',
  '- analyze: likely vulnerable, needs deep review',
  '- hold: uncertain, keep for later review',
  '- drop: clearly safe, no vulnerability possible',
].join('\n');

const formatCandidatesForDiscovery = (units: MergedSecurityReviewUnit[]): string => {
  return units.map((u, i) => [
    `[ID: ${u.id}] (${u.candidateKind})`,
    `File: ${u.filePath}:${u.startLine}-${u.endLine}`,
    u.symbolName ? `Symbol: ${u.symbolName}` : '',
    u.sourceKind ? `Source: ${u.sourceKind}` : '',
    u.sinkKind ? `Sink: ${u.sinkKind}` : '',
    '```',
    u.codeSnippet.slice(0, 500),
    '```',
    '',
  ].filter(Boolean).join('\n')).join('\n---\n');
};

const runDiscoveryBatch = async (batch: DiscoveryBatch): Promise<DiscoveryResult> => {
  const llmEnabled = isAnyLlmConfigured();
  if (!llmEnabled) {
    // No LLM: include everything for safety
    return {
      analyze: batch.units.map((u) => ({
        unitId: u.id,
        disposition: 'analyze' as const,
        priorityScore: 50,
        shortReason: 'LLM unavailable — included by default',
        reasonCodes: ['NO_LLM'],
      })),
      hold: [],
      drop: [],
    };
  }

  const userPrompt = [
    `Batch ${batch.batchIndex + 1}: Triage the following ${batch.units.length} security candidates.`,
    '',
    formatCandidatesForDiscovery(batch.units),
  ].join('\n');

  try {
    const raw = await generateText({
      system: DISCOVERY_SYSTEM,
      user: userPrompt,
      actionName: 'security.discovery',
      temperature: 0.1,
      maxTokens: 2000,
    });

    // Extract JSON from response
    const jsonMatch = raw.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      // Parse failure: include everything
      return {
        analyze: batch.units.map((u) => ({
          unitId: u.id,
          disposition: 'analyze' as const,
          priorityScore: 50,
          shortReason: 'LLM response parse failed — included by default',
          reasonCodes: ['PARSE_FAILED'],
        })),
        hold: [],
        drop: [],
      };
    }

    const parsed = JSON.parse(jsonMatch[0]);
    return normalizeDiscoveryResult(parsed);
  } catch {
    // Error: include everything
    return {
      analyze: batch.units.map((u) => ({
        unitId: u.id,
        disposition: 'analyze' as const,
        priorityScore: 50,
        shortReason: 'Discovery error — included by default',
        reasonCodes: ['DISCOVERY_ERROR'],
      })),
      hold: [],
      drop: [],
    };
  }
};

// ──── Analysis Phase ───────────────────────────────────────────────────────────

const ANALYSIS_SYSTEM = [
  'You are a Security Analysis agent performing deep vulnerability analysis.',
  'You have access to code snippets from the Discovery phase.',
  '',
  'For each candidate, determine:',
  '1. Is there an actual exploitable vulnerability?',
  '2. What is the concrete attack scenario?',
  '3. What is the recommended fix?',
  '',
  'OUTPUT: JSON array of AnalysisVerdict objects:',
  '[{',
  '  "unitId": "...",',
  '  "disposition": "confirmed|likely|needs_review|dismissed",',
  '  "confidence": "high|medium|low",',
  '  "rationale": "Concrete explanation of the vulnerability and attack scenario",',
  '  "relatedCandidateIds": ["..."],',
  '  "findingTitle": "Short title for the finding"',
  '}]',
  '',
  'Only report confidence >= medium findings as confirmed/likely.',
  'Be specific about attack scenarios — no generic warnings.',
].join('\n');

const formatCandidatesForAnalysis = (
  units: MergedSecurityReviewUnit[],
): string => {
  return units.map((u) => [
    `[ID: ${u.id}]`,
    `Kind: ${u.candidateKind}`,
    `File: ${u.filePath}:${u.startLine}-${u.endLine}`,
    u.symbolName ? `Symbol: ${u.symbolName}` : '',
    u.sourceKind ? `Source: ${u.sourceKind}` : '',
    u.sinkKind ? `Sink: ${u.sinkKind}` : '',
    '```',
    u.codeSnippet.slice(0, 800),
    '```',
    '',
  ].filter(Boolean).join('\n')).join('\n---\n');
};

const runAnalysisBatch = async (
  units: MergedSecurityReviewUnit[],
): Promise<AnalysisVerdict[]> => {
  const llmEnabled = isAnyLlmConfigured();
  if (!llmEnabled) {
    return units.map((u) => ({
      unitId: u.id,
      disposition: 'needs_review' as const,
      confidence: 'low' as const,
      rationale: 'LLM unavailable — manual review required',
      relatedCandidateIds: u.rawCandidateIds,
      findingTitle: `Review: ${u.candidateKind} in ${u.filePath}`,
    }));
  }

  const userPrompt = [
    `Analyze the following ${units.length} security candidates for real vulnerabilities:`,
    '',
    formatCandidatesForAnalysis(units),
  ].join('\n');

  try {
    const raw = await generateText({
      system: ANALYSIS_SYSTEM,
      user: userPrompt,
      actionName: 'security.analysis',
      temperature: 0.1,
      maxTokens: 3000,
    });

    // Extract JSON array from response
    const jsonMatch = raw.match(/\[[\s\S]*\]/);
    if (!jsonMatch) {
      return units.map((u) => ({
        unitId: u.id,
        disposition: 'needs_review' as const,
        confidence: 'low' as const,
        rationale: 'Analysis response parse failed',
        relatedCandidateIds: u.rawCandidateIds,
      }));
    }

    const parsed = JSON.parse(jsonMatch[0]) as unknown[];
    return parsed.map((item) => normalizeAnalysisVerdict(item));
  } catch {
    return units.map((u) => ({
      unitId: u.id,
      disposition: 'needs_review' as const,
      confidence: 'low' as const,
      rationale: 'Analysis error — manual review required',
      relatedCandidateIds: u.rawCandidateIds,
    }));
  }
};

// ──── Full Pipeline ────────────────────────────────────────────────────────────

export const runSecurityPipeline = async (options?: {
  repoId?: string;
  targetPath?: string;
  candidateKind?: string;
}): Promise<SecurityPipelineResult> => {
  const startMs = Date.now();
  const repoId = options?.repoId || 'muel-backend';

  // Step 1: Load candidates from JSONL
  let candidateResult: Awaited<ReturnType<typeof listSecurityCandidates>>;
  try {
    candidateResult = await listSecurityCandidates({
      repoId,
      view: 'merged',
      candidateKind: options?.candidateKind,
      limit: MAX_CANDIDATES_TO_PROCESS,
    });
  } catch {
    return {
      ok: false,
      totalCandidates: 0,
      discoveryIncluded: 0,
      discoveryExcluded: 0,
      analysisVerdicts: [],
      confirmedFindings: [],
      summary: 'No security candidates found. Run `npm run security:scan` first to generate tmp/security-candidates/latest.jsonl',
      durationMs: Date.now() - startMs,
    };
  }

  const mergedUnits = (candidateResult.items || []) as MergedSecurityReviewUnit[];
  if (mergedUnits.length === 0) {
    return {
      ok: true,
      totalCandidates: 0,
      discoveryIncluded: 0,
      discoveryExcluded: 0,
      analysisVerdicts: [],
      confirmedFindings: [],
      summary: 'No security candidates in JSONL file. Codebase may be clean or scanner needs configuration.',
      durationMs: Date.now() - startMs,
    };
  }

  // Filter by target path if specified
  let filteredUnits = mergedUnits;
  if (options?.targetPath) {
    const targetLower = options.targetPath.toLowerCase();
    filteredUnits = mergedUnits.filter((u) => u.filePath.toLowerCase().includes(targetLower));
  }

  // Step 2: Discovery phase — batch triage
  const discoveryBatches: DiscoveryBatch[] = [];
  for (let i = 0; i < filteredUnits.length; i += DISCOVERY_BATCH_SIZE) {
    discoveryBatches.push({
      units: filteredUnits.slice(i, i + DISCOVERY_BATCH_SIZE),
      batchIndex: discoveryBatches.length,
    });
  }

  const allDiscoveryResults: DiscoveryResult[] = [];
  for (const batch of discoveryBatches) {
    allDiscoveryResults.push(await runDiscoveryBatch(batch));
  }

  // Collect analyze-worthy unit IDs
  const analyzeUnitIds = new Set<string>();
  let holdCount = 0;
  let dropCount = 0;
  for (const dr of allDiscoveryResults) {
    for (const d of dr.analyze) analyzeUnitIds.add(d.unitId);
    holdCount += dr.hold.length;
    dropCount += dr.drop.length;
  }

  // Include hold items too (better to over-analyze than miss)
  for (const dr of allDiscoveryResults) {
    for (const d of dr.hold) analyzeUnitIds.add(d.unitId);
  }

  const unitsToAnalyze = filteredUnits.filter((u) => analyzeUnitIds.has(u.id));

  // Step 3: Analysis phase — deep review
  const allVerdicts: AnalysisVerdict[] = [];
  for (let i = 0; i < unitsToAnalyze.length; i += ANALYSIS_BATCH_SIZE) {
    const batch = unitsToAnalyze.slice(i, i + ANALYSIS_BATCH_SIZE);
    const batchVerdicts = await runAnalysisBatch(batch);
    allVerdicts.push(...batchVerdicts);
  }

  const confirmed = allVerdicts.filter(
    (v) => v.disposition === 'confirmed' || v.disposition === 'likely',
  );

  // Build summary
  const summaryLines = [
    `# Security Pipeline Report`,
    ``,
    `## Statistics`,
    `- Total candidates: ${filteredUnits.length}`,
    `- Discovery → Analyze: ${analyzeUnitIds.size}`,
    `- Discovery → Hold: ${holdCount}`,
    `- Discovery → Drop: ${dropCount}`,
    `- Analysis verdicts: ${allVerdicts.length}`,
    `- Confirmed/Likely findings: ${confirmed.length}`,
    ``,
  ];

  if (confirmed.length > 0) {
    summaryLines.push(`## Findings`);
    for (const v of confirmed) {
      summaryLines.push(
        ``,
        `### ${v.findingTitle || v.unitId}`,
        `- Disposition: ${v.disposition} (${v.confidence} confidence)`,
        `- Rationale: ${v.rationale}`,
      );
    }
  } else {
    summaryLines.push(`## Result`, `No confirmed vulnerabilities found above confidence threshold.`);
  }

  return {
    ok: true,
    totalCandidates: filteredUnits.length,
    discoveryIncluded: analyzeUnitIds.size,
    discoveryExcluded: dropCount,
    analysisVerdicts: allVerdicts,
    confirmedFindings: confirmed,
    summary: summaryLines.join('\n'),
    durationMs: Date.now() - startMs,
  };
};
