-- Migration 007: Workflow tables + traffic routing infrastructure
-- Formalizes workflow_sessions/steps/events from MIGRATION_AGENT_WEEKLY_REPORTS.sql
-- Adds traffic_routing_decisions for LangGraph Phase 2 cutover audit trail
-- Apply in Supabase SQL Editor (idempotent)

-- ────────────────────────────────────────────────────────────────────
-- 1. Workflow Sessions (was only in planning migration, never formalized)
-- ────────────────────────────────────────────────────────────────────

create table if not exists public.workflow_sessions (
  id bigint generated by default as identity primary key,
  session_id text not null unique,
  workflow_name text not null,
  stage text not null,
  scope text,
  status text not null,
  metadata jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (status in ('proposed', 'classified', 'routed', 'executing', 'verifying', 'approving', 'released', 'recovering', 'failed'))
);

create table if not exists public.workflow_steps (
  id bigint generated by default as identity primary key,
  session_id text not null references public.workflow_sessions(session_id) on delete cascade,
  step_order integer not null,
  step_name text not null,
  agent_role text,
  status text not null,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  duration_ms integer,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (status in ('queued', 'running', 'passed', 'failed', 'skipped'))
);

create unique index if not exists idx_workflow_steps_session_order
  on public.workflow_steps (session_id, step_order);

create table if not exists public.workflow_events (
  id bigint generated by default as identity primary key,
  session_id text not null references public.workflow_sessions(session_id) on delete cascade,
  event_type text not null,
  from_state text,
  to_state text,
  handoff_from text,
  handoff_to text,
  decision_reason text,
  evidence_id text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_workflow_sessions_status_started
  on public.workflow_sessions (status, started_at desc);

create index if not exists idx_workflow_steps_session_status
  on public.workflow_steps (session_id, status);

create index if not exists idx_workflow_events_session_created
  on public.workflow_events (session_id, created_at desc);

-- updated_at triggers (reuse set_updated_at from earlier migrations)
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_workflow_sessions_updated_at on public.workflow_sessions;
create trigger trg_workflow_sessions_updated_at
before update on public.workflow_sessions
for each row
execute function public.set_updated_at();

drop trigger if exists trg_workflow_steps_updated_at on public.workflow_steps;
create trigger trg_workflow_steps_updated_at
before update on public.workflow_steps
for each row
execute function public.set_updated_at();

-- RLS: service_role only
alter table public.workflow_sessions enable row level security;
alter table public.workflow_steps enable row level security;
alter table public.workflow_events enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='workflow_sessions' and policyname='workflow_sessions_service_role') then
    create policy workflow_sessions_service_role on public.workflow_sessions
      for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
  end if;

  if not exists (select 1 from pg_policies where schemaname='public' and tablename='workflow_steps' and policyname='workflow_steps_service_role') then
    create policy workflow_steps_service_role on public.workflow_steps
      for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
  end if;

  if not exists (select 1 from pg_policies where schemaname='public' and tablename='workflow_events' and policyname='workflow_events_service_role') then
    create policy workflow_events_service_role on public.workflow_events
      for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
  end if;
end
$$;

-- ────────────────────────────────────────────────────────────────────
-- 2. Traffic Routing Decisions — audit trail for LangGraph Phase 2
-- ────────────────────────────────────────────────────────────────────

create table if not exists public.traffic_routing_decisions (
  id bigint generated always as identity primary key,
  session_id text not null,
  guild_id text not null,
  route text not null,                -- 'main' | 'shadow' | 'langgraph'
  reason text not null,               -- human-readable decision reason
  got_cutover_allowed boolean,
  rollout_percentage integer,
  stable_bucket integer,
  shadow_divergence_rate real,        -- rolling diverge rate at decision time
  shadow_quality_delta real,          -- avg quality delta at decision time
  readiness_recommended boolean,
  policy_snapshot jsonb not null default '{}'::jsonb,
  workflow_session_id text,           -- FK to workflow_sessions (NULL for main-only)
  sprint_pipeline_id text,            -- FK to sprint_pipelines (NULL for non-sprint)
  created_at timestamptz not null default now()
);

create index if not exists idx_traffic_routing_decisions_guild_created
  on public.traffic_routing_decisions (guild_id, created_at desc);

create index if not exists idx_traffic_routing_decisions_session
  on public.traffic_routing_decisions (session_id);

create index if not exists idx_traffic_routing_decisions_route
  on public.traffic_routing_decisions (route, created_at desc);

-- RLS: service_role only
alter table public.traffic_routing_decisions enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='traffic_routing_decisions' and policyname='traffic_routing_decisions_service_role') then
    create policy traffic_routing_decisions_service_role on public.traffic_routing_decisions
      for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
  end if;
end
$$;

-- ────────────────────────────────────────────────────────────────────
-- 3. Add cross-reference columns to shadow_graph_divergence_logs
-- ────────────────────────────────────────────────────────────────────

do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'shadow_graph_divergence_logs'
      and column_name = 'traffic_routing_decision_id'
  ) then
    alter table public.shadow_graph_divergence_logs
      add column traffic_routing_decision_id bigint;
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'shadow_graph_divergence_logs'
      and column_name = 'workflow_session_id'
  ) then
    alter table public.shadow_graph_divergence_logs
      add column workflow_session_id text;
  end if;
end
$$;
