/* eslint-disable no-console */
/**
 * obsidian-wiki-pr.ts
 *
 * Full LLM-Wiki → GitHub PR pipeline:
 *   1. Checks out a dated branch in the vault git repo
 *   2. Stages and commits all markdown changes
 *   3. Pushes the branch to origin
 *   4. Creates a pull request via the GitHub REST API
 *
 * Usage:
 *   tsx scripts/obsidian-wiki-pr.ts [--vault <path>] [--label <label>] [--base <branch>] [--dry-run]
 *
 * Required env:
 *   OBSIDIAN_SYNC_VAULT_PATH  or  OBSIDIAN_VAULT_PATH  — local vault git repo path
 *   OBSIDIAN_VAULT_GITHUB_OWNER                        — GitHub owner of the vault repo
 *   OBSIDIAN_VAULT_GITHUB_REPO                         — GitHub repo name of the vault
 *   SPRINT_GITHUB_TOKEN  or  GITHUB_TOKEN              — PAT with repo scope
 *
 * Optional env:
 *   DRY_RUN=true  — skip commit/push/PR (prints what would happen)
 */
import 'dotenv/config';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import path from 'node:path';
import { stat } from 'node:fs/promises';

const execFileAsync = promisify(execFile);

const VAULT_GITHUB_OWNER = String(process.env.OBSIDIAN_VAULT_GITHUB_OWNER ?? '').trim();
const VAULT_GITHUB_REPO = String(process.env.OBSIDIAN_VAULT_GITHUB_REPO ?? '').trim();
const GITHUB_TOKEN = String(process.env.SPRINT_GITHUB_TOKEN ?? process.env.GITHUB_TOKEN ?? '').trim();

type ParsedArgs = {
  vaultPath: string;
  branch: string;
  base: string;
  commitMsg: string;
  dryRun: boolean;
  today: string;
};

const parseArgs = (): ParsedArgs => {
  const args = process.argv.slice(2);
  let vaultPath = String(process.env.OBSIDIAN_SYNC_VAULT_PATH ?? process.env.OBSIDIAN_VAULT_PATH ?? '').trim();
  const today = new Date().toISOString().slice(0, 10);
  let label = 'ingest';
  let base = 'main';
  let dryRun = String(process.env.DRY_RUN ?? '').toLowerCase() === 'true';

  for (let i = 0; i < args.length; i += 1) {
    const current = String(args[i] ?? '').trim();
    if (current === '--vault' || current === '--vault-path') {
      const value = String(args[i + 1] ?? '').trim();
      if (value) {
        vaultPath = value;
        i += 1;
      }
    } else if (current === '--label') {
      const value = String(args[i + 1] ?? '').trim();
      if (value) {
        label = value;
        i += 1;
      }
    } else if (current === '--base') {
      const value = String(args[i + 1] ?? '').trim();
      if (value) {
        base = value;
        i += 1;
      }
    } else if (current === '--dry-run') {
      dryRun = true;
    }
  }

  const branch = `wiki/${today}-${label}`;
  const commitMsg = `wiki: ${label} ${today}`;
  return { vaultPath, branch, base, commitMsg, dryRun, today };
};

const git = async (cwd: string, ...args: string[]): Promise<string> => {
  const { stdout } = await execFileAsync('git', args, { cwd });
  return stdout.trim();
};

const ensureVaultDir = async (vaultPath: string): Promise<string> => {
  const trimmed = vaultPath.trim();
  if (!trimmed) {
    throw new Error('vault path is required. Set OBSIDIAN_SYNC_VAULT_PATH or OBSIDIAN_VAULT_PATH');
  }
  const resolved = path.resolve(trimmed);
  const info = await stat(resolved);
  if (!info.isDirectory()) {
    throw new Error(`vault path is not a directory: ${resolved}`);
  }
  return resolved;
};

type PrPayload = {
  title: string;
  body: string;
  head: string;
  base: string;
  draft: boolean;
};

const createPullRequest = async (payload: PrPayload): Promise<{ number: number; html_url: string }> => {
  const url = `https://api.github.com/repos/${VAULT_GITHUB_OWNER}/${VAULT_GITHUB_REPO}/pulls`;
  const res = await fetch(url, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${GITHUB_TOKEN}`,
      'Accept': 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
      'X-GitHub-Api-Version': '2022-11-28',
    },
    body: JSON.stringify(payload),
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`GitHub API ${String(res.status)}: ${text.slice(0, 300)}`);
  }

  return res.json() as Promise<{ number: number; html_url: string }>;
};

const buildPrBody = (today: string, branch: string): string =>
  [
    '## LLM-Wiki Ingest\n',
    `Automated vault update for **${today}** — branch \`${branch}\`.`,
    '',
    '### Review checklist',
    '- [ ] No sensitive or PII data in new/updated pages',
    '- [ ] Cross-references and backlinks are consistent',
    '- [ ] No orphan pages (pages with zero inbound links) introduced',
    '- [ ] `npm run obsidian:audit` passes locally',
    '',
    '> Auto-generated by `scripts/obsidian-wiki-pr.ts`',
  ].join('\n');

const main = async (): Promise<void> => {
  const { vaultPath, branch, base, commitMsg, dryRun, today } = parseArgs();

  if (!VAULT_GITHUB_OWNER || !VAULT_GITHUB_REPO) {
    console.error('[wiki-pr] OBSIDIAN_VAULT_GITHUB_OWNER and OBSIDIAN_VAULT_GITHUB_REPO are required');
    process.exit(2);
  }
  if (!GITHUB_TOKEN) {
    console.error('[wiki-pr] SPRINT_GITHUB_TOKEN or GITHUB_TOKEN is required');
    process.exit(2);
  }

  const resolved = await ensureVaultDir(vaultPath);
  console.log(`[wiki-pr] vault=${resolved} branch=${branch} base=${base} dryRun=${String(dryRun)}`);

  // ── 1. Check for changes ────────────────────────────────────────────────────
  const status = await git(resolved, 'status', '--porcelain');
  if (!status) {
    console.log('[wiki-pr] no changes in vault — nothing to PR');
    return;
  }
  const lineCount = status.split('\n').filter(Boolean).length;
  console.log(`[wiki-pr] ${String(lineCount)} file(s) changed`);

  if (dryRun) {
    console.log('[wiki-pr] dry-run: would create branch, commit, push, and open PR');
    console.log(`  branch  : ${branch}`);
    console.log(`  commit  : ${commitMsg}`);
    console.log(`  pr title: wiki: ingest ${today}`);
    console.log(status);
    return;
  }

  // ── 2. Create local branch ──────────────────────────────────────────────────
  try {
    await git(resolved, 'checkout', '-b', branch);
  } catch {
    // Branch already exists locally — reuse it
    await git(resolved, 'checkout', branch);
  }
  console.log(`[wiki-pr] checked out: ${branch}`);

  // ── 3. Stage and commit ─────────────────────────────────────────────────────
  await git(resolved, 'add', '--all');
  const commitOut = await git(resolved, 'commit', '--message', commitMsg);
  console.log(`[wiki-pr] committed: ${commitOut.split('\n')[0] ?? ''}`);

  // ── 4. Push ─────────────────────────────────────────────────────────────────
  await git(resolved, 'push', '--set-upstream', 'origin', branch);
  console.log(`[wiki-pr] pushed: ${branch}`);

  // ── 5. Create PR ────────────────────────────────────────────────────────────
  const pr = await createPullRequest({
    title: `wiki: ingest ${today}`,
    body: buildPrBody(today, branch),
    head: branch,
    base,
    draft: false,
  });

  console.log(`[wiki-pr] PR created: #${String(pr.number)} ${pr.html_url}`);
};

main().catch((error) => {
  console.error('[wiki-pr] error:', error instanceof Error ? error.message : String(error));
  process.exit(1);
});
