-- Migration: autonomy reporting baseline
-- Date: 2026-04-11
-- Purpose:
--   1. Ensure weekly autonomy reporting tables exist in named migration form
--   2. Align report_kind and job_type constraints with current runtime usage
--   3. Backfill triggers, indexes, and baseline RLS policies for missing environments
--
-- Safe to re-run.

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.memory_jobs (
  id text primary key,
  guild_id text not null,
  job_type text not null,
  status text not null default 'queued',
  next_attempt_at timestamptz not null default now(),
  window_started_at timestamptz,
  window_ended_at timestamptz,
  input jsonb,
  output jsonb,
  error text,
  deadlettered_at timestamptz,
  deadletter_reason text,
  attempts integer not null default 0,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (job_type in ('short_summary', 'topic_synthesis', 'durable_extraction', 'reindex', 'conflict_scan', 'onboarding_snapshot', 'consolidation')),
  check (status in ('queued', 'running', 'completed', 'failed', 'canceled'))
);

alter table public.memory_jobs add column if not exists next_attempt_at timestamptz;
alter table public.memory_jobs add column if not exists deadlettered_at timestamptz;
alter table public.memory_jobs add column if not exists deadletter_reason text;

update public.memory_jobs
set next_attempt_at = coalesce(next_attempt_at, created_at, now())
where next_attempt_at is null;

alter table public.memory_jobs alter column next_attempt_at set default now();
alter table public.memory_jobs alter column next_attempt_at set not null;

alter table public.memory_jobs drop constraint if exists memory_jobs_job_type_check;
alter table public.memory_jobs
  add constraint memory_jobs_job_type_check
  check (job_type in ('short_summary', 'topic_synthesis', 'durable_extraction', 'reindex', 'conflict_scan', 'onboarding_snapshot', 'consolidation'));

create index if not exists idx_memory_jobs_guild_status_created
  on public.memory_jobs (guild_id, status, created_at desc);

create index if not exists idx_memory_jobs_type_status
  on public.memory_jobs (job_type, status, created_at desc);

create index if not exists idx_memory_jobs_status_next_attempt
  on public.memory_jobs (status, next_attempt_at asc)
  where status = 'queued';

drop trigger if exists trg_memory_jobs_updated_at on public.memory_jobs;
create trigger trg_memory_jobs_updated_at
before update on public.memory_jobs
for each row
execute function public.set_updated_at();

create table if not exists public.memory_job_deadletters (
  id bigint generated by default as identity primary key,
  job_id text,
  guild_id text not null,
  job_type text not null,
  attempts integer not null,
  error text not null,
  input jsonb,
  output jsonb,
  recovery_status text not null default 'pending',
  recovery_attempts integer not null default 0,
  recovered_at timestamptz,
  last_recovery_error text,
  failed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (job_type in ('short_summary', 'topic_synthesis', 'durable_extraction', 'reindex', 'conflict_scan', 'onboarding_snapshot', 'consolidation')),
  check (recovery_status in ('pending', 'requeued', 'ignored')),
  check (recovery_attempts >= 0)
);

alter table public.memory_job_deadletters add column if not exists recovery_status text;
alter table public.memory_job_deadletters add column if not exists recovery_attempts integer;
alter table public.memory_job_deadletters add column if not exists recovered_at timestamptz;
alter table public.memory_job_deadletters add column if not exists last_recovery_error text;
alter table public.memory_job_deadletters add column if not exists updated_at timestamptz;

update public.memory_job_deadletters
set recovery_status = coalesce(recovery_status, 'pending')
where recovery_status is null;

update public.memory_job_deadletters
set recovery_attempts = coalesce(recovery_attempts, 0)
where recovery_attempts is null;

update public.memory_job_deadletters
set updated_at = coalesce(updated_at, created_at, now())
where updated_at is null;

alter table public.memory_job_deadletters alter column recovery_status set default 'pending';
alter table public.memory_job_deadletters alter column recovery_status set not null;
alter table public.memory_job_deadletters alter column recovery_attempts set default 0;
alter table public.memory_job_deadletters alter column recovery_attempts set not null;
alter table public.memory_job_deadletters alter column updated_at set default now();
alter table public.memory_job_deadletters alter column updated_at set not null;

alter table public.memory_job_deadletters drop constraint if exists memory_job_deadletters_job_type_check;
alter table public.memory_job_deadletters
  add constraint memory_job_deadletters_job_type_check
  check (job_type in ('short_summary', 'topic_synthesis', 'durable_extraction', 'reindex', 'conflict_scan', 'onboarding_snapshot', 'consolidation'));

create index if not exists idx_memory_job_deadletters_guild_created
  on public.memory_job_deadletters (guild_id, created_at desc);

create index if not exists idx_memory_job_deadletters_job_id
  on public.memory_job_deadletters (job_id);

create index if not exists idx_memory_job_deadletters_recovery
  on public.memory_job_deadletters (recovery_status, created_at desc);

drop trigger if exists trg_memory_job_deadletters_updated_at on public.memory_job_deadletters;
create trigger trg_memory_job_deadletters_updated_at
before update on public.memory_job_deadletters
for each row
execute function public.set_updated_at();

create table if not exists public.agent_llm_call_logs (
  id bigint generated by default as identity primary key,
  guild_id text,
  session_id text,
  requested_by text,
  action_name text,
  provider text not null,
  model text,
  experiment_name text,
  experiment_arm text,
  experiment_key_hash text,
  latency_ms integer not null default 0,
  success boolean not null default true,
  error_code text,
  prompt_chars integer not null default 0,
  output_chars integer not null default 0,
  avg_logprob numeric(10, 6),
  estimated_cost_usd numeric(12, 6),
  created_at timestamptz not null default now(),
  check (latency_ms >= 0),
  check (prompt_chars >= 0),
  check (output_chars >= 0),
  check (estimated_cost_usd is null or estimated_cost_usd >= 0)
);

create index if not exists idx_agent_llm_call_logs_guild_created
  on public.agent_llm_call_logs (guild_id, created_at desc);

create index if not exists idx_agent_llm_call_logs_provider_created
  on public.agent_llm_call_logs (provider, created_at desc);

create index if not exists idx_agent_llm_call_logs_experiment
  on public.agent_llm_call_logs (experiment_name, experiment_arm, created_at desc);

create table if not exists public.agent_weekly_reports (
  id bigint generated by default as identity primary key,
  report_key text not null unique,
  report_kind text not null,
  guild_id text,
  provider text,
  action_prefix text,
  baseline_from timestamptz,
  baseline_to timestamptz,
  candidate_from timestamptz,
  candidate_to timestamptz,
  baseline_summary jsonb not null default '{}'::jsonb,
  candidate_summary jsonb not null default '{}'::jsonb,
  delta_summary jsonb not null default '{}'::jsonb,
  top_actions jsonb not null default '{}'::jsonb,
  markdown text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (report_kind in ('llm_latency_weekly', 'go_no_go_weekly', 'hybrid_weekly', 'rollback_rehearsal_weekly', 'memory_queue_weekly', 'self_improvement_patterns', 'jarvis_optimize_result', 'cross_loop_origin', 'convergence_report'))
);

alter table public.agent_weekly_reports drop constraint if exists agent_weekly_reports_report_kind_check;
alter table public.agent_weekly_reports
  add constraint agent_weekly_reports_report_kind_check
  check (
    report_kind in (
      'llm_latency_weekly',
      'go_no_go_weekly',
      'hybrid_weekly',
      'rollback_rehearsal_weekly',
      'memory_queue_weekly',
      'self_improvement_patterns',
      'jarvis_optimize_result',
      'cross_loop_origin',
      'convergence_report'
    )
  );

create index if not exists idx_agent_weekly_reports_kind_created
  on public.agent_weekly_reports (report_kind, created_at desc);

create index if not exists idx_agent_weekly_reports_guild_created
  on public.agent_weekly_reports (guild_id, created_at desc);

drop trigger if exists trg_agent_weekly_reports_updated_at on public.agent_weekly_reports;
create trigger trg_agent_weekly_reports_updated_at
before update on public.agent_weekly_reports
for each row
execute function public.set_updated_at();

alter table public.memory_jobs enable row level security;
alter table public.memory_job_deadletters enable row level security;
alter table public.agent_llm_call_logs enable row level security;
alter table public.agent_weekly_reports enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'memory_jobs'
      and policyname = 'memory_jobs_guild_all'
  ) then
    create policy memory_jobs_guild_all on public.memory_jobs
      for all
      using (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''))
      with check (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'memory_job_deadletters'
      and policyname = 'memory_deadletters_guild_all'
  ) then
    create policy memory_deadletters_guild_all on public.memory_job_deadletters
      for all
      using (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''))
      with check (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'agent_llm_call_logs'
      and policyname = 'agent_llm_call_logs_guild_all'
  ) then
    create policy agent_llm_call_logs_guild_all on public.agent_llm_call_logs
      for all
      using (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''))
      with check (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'agent_weekly_reports'
      and policyname = 'agent_weekly_reports_guild_all'
  ) then
    create policy agent_weekly_reports_guild_all on public.agent_weekly_reports
      for all
      using (auth.role() = 'service_role' or coalesce(guild_id, '') = coalesce(auth.jwt() ->> 'guild_id', ''))
      with check (auth.role() = 'service_role' or coalesce(guild_id, '') = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;
end
$$;

do $$
begin
  if to_regclass('public.schema_migrations') is not null then
    insert into public.schema_migrations (name, applied_by)
    values ('MIGRATION_AUTONOMY_REPORTING_BASELINE', 'manual')
    on conflict (name) do nothing;
  end if;
end
$$;