-- Supabase schema bootstrap (idempotent)
-- Run in Supabase SQL Editor.

-- ==========================================
-- 1. Initial reset (optional)
-- ==========================================
-- drop table if exists public.error_history cascade;
-- drop table if exists public.macro_data cascade;
-- drop table if exists public.macro_series cascade;
-- drop table if exists public.logs cascade;
-- drop table if exists public.settings cascade;
-- drop table if exists public.alert_slots cascade;
-- drop table if exists public.sources cascade;
-- drop table if exists public.users cascade;

-- ==========================================
-- 2. User and service infrastructure
-- ==========================================

create table if not exists public.users (
  id text primary key,
  username text not null,
  avatar text,
  discord_access_token text,
  discord_refresh_token text,
  created_at timestamptz default current_timestamp,
  updated_at timestamptz default current_timestamp
);

create table if not exists public.sources (
  id serial primary key,
  user_id text references public.users(id) on delete set null,
  name text not null,
  url text not null unique,
  guild_id text,
  channel_id text,
  guild_name text,
  channel_name text,
  is_active boolean not null default true,
  lock_token text,
  lock_expires_at timestamptz,
  last_post_id text,
  last_post_signature text,
  last_check_status text,
  last_check_error text,
  last_check_at timestamptz,
  created_at timestamptz default current_timestamp
);

-- Node-only migration safety: add columns when table already exists from older schema.
alter table public.sources add column if not exists guild_id text;
alter table public.sources add column if not exists channel_id text;
alter table public.sources add column if not exists guild_name text;
alter table public.sources add column if not exists channel_name text;
alter table public.sources add column if not exists is_active boolean not null default true;
alter table public.sources add column if not exists lock_token text;
alter table public.sources add column if not exists lock_expires_at timestamptz;

create index if not exists idx_sources_guild_channel on public.sources (guild_id, channel_id);
create index if not exists idx_sources_lock on public.sources (lock_token, lock_expires_at);

create table if not exists public.alert_slots (
  id serial primary key,
  user_id text not null references public.users(id) on delete cascade,
  source_id int not null references public.sources(id) on delete cascade,
  guild_id text not null,
  channel_id text not null,
  guild_name text,
  channel_name text,
  is_active boolean default true,
  created_at timestamptz default current_timestamp,
  unique(source_id, channel_id)
);

create table if not exists public.settings (
  key text,
  user_id text references public.users(id) on delete cascade,
  value text not null,
  updated_at timestamptz default current_timestamp,
  primary key (key, user_id)
);

create table if not exists public.logs (
  id serial primary key,
  user_id text references public.users(id) on delete cascade,
  message text not null,
  type text not null,
  created_at timestamptz default current_timestamp
);

-- ==========================================
-- 3. Macro indicator infrastructure
-- ==========================================

create table if not exists public.macro_series (
  series_id text primary key,
  name text not null,
  frequency text,
  description text,
  last_updated timestamptz default now()
);

create table if not exists public.macro_data (
  id serial primary key,
  series_id text references public.macro_series(series_id) on delete cascade,
  date date not null,
  value numeric not null,
  created_at timestamptz default now(),
  unique(series_id, date)
);

insert into public.macro_series (series_id, name, frequency, description) values
('CPIAUCSL', 'Consumer Price Index (CPI)', 'Monthly', 'US urban consumer price index'),
('FEDFUNDS', 'Federal Funds Rate', 'Monthly', 'US central bank policy rate'),
('T10Y2Y', 'Yield Spread (10Y-2Y)', 'Daily', 'Treasury curve inversion indicator'),
('M2SL', 'M2 Money Stock', 'Monthly', 'Broad money supply')
on conflict (series_id) do update
set name = excluded.name,
    frequency = excluded.frequency,
    description = excluded.description;

-- ==========================================
-- 4. Error logging optimization
-- ==========================================

create table if not exists public.error_history (
  id serial primary key,
  source_id int references public.sources(id) on delete cascade,
  error_message text not null,
  occurred_at timestamptz default now()
);

create table if not exists public.system_error_events (
  id bigint generated by default as identity primary key,
  code text not null,
  source text not null,
  severity text not null default 'error',
  message text not null,
  stack text,
  guild_id text,
  session_id text,
  action_name text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_system_error_events_created_at
  on public.system_error_events (created_at desc);

create index if not exists idx_system_error_events_code
  on public.system_error_events (code, created_at desc);

create index if not exists idx_system_error_events_guild
  on public.system_error_events (guild_id, created_at desc);

create or replace function public.log_source_error()
returns trigger
language plpgsql
as $$
begin
  if (new.last_check_status = 'error' and old.last_check_status is distinct from 'error') then
    insert into public.error_history (source_id, error_message)
    values (new.id, new.last_check_error);
  end if;
  return new;
end;
$$;

drop trigger if exists trigger_log_error on public.sources;
create trigger trigger_log_error
after update on public.sources
for each row
execute function public.log_source_error();

-- ==========================================
-- 5. Orphan source cleanup trigger
-- ==========================================

create or replace function public.delete_orphaned_source()
returns trigger
language plpgsql
as $$
begin
  if not exists (select 1 from public.alert_slots where source_id = old.source_id) then
    delete from public.sources where id = old.source_id;
  end if;
  return old;
end;
$$;

drop trigger if exists trigger_delete_orphaned_source on public.alert_slots;
create trigger trigger_delete_orphaned_source
after delete on public.alert_slots
for each row
execute function public.delete_orphaned_source();

-- ==========================================
-- 6. TradingView signal pipeline
-- ==========================================

create table if not exists public.trading_signals (
  id serial primary key,
  symbol text not null,
  signal_type text not null,
  price numeric,
  qty numeric,
  leverage int default 1,
  received_at timestamptz default now()
);

-- ==========================================
-- 7. Quant regime master
-- ==========================================

create table if not exists public.market_regime (
  date date primary key,
  regime_phase text not null,
  inflation_score numeric,
  growth_score numeric,
  description text,
  updated_at timestamptz default now()
);

-- ==========================================
-- 8. User roles
-- ==========================================

create table if not exists public.user_roles (
  user_id text primary key,
  role text not null default 'user',
  granted_at timestamptz default current_timestamp,
  granted_by text
);

create index if not exists idx_user_roles_role on public.user_roles(role);

create table if not exists public.discord_login_sessions (
  guild_id text not null,
  user_id text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (guild_id, user_id)
);

create index if not exists idx_discord_login_sessions_expires_at
  on public.discord_login_sessions (expires_at);

-- Replace with real Discord user id before production use.
insert into public.user_roles (user_id, role)
values ('123456789012345678', 'admin')
on conflict (user_id) do update
set role = 'admin';

-- ==========================================
-- 9. Common updated_at trigger helper
-- ==========================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_discord_login_sessions_updated_at on public.discord_login_sessions;
create trigger trg_discord_login_sessions_updated_at
before update on public.discord_login_sessions
for each row
execute function public.set_updated_at();

-- ==========================================
-- 10. Trading backend runtime tables
-- ==========================================

create table if not exists public.trades (
  id bigint generated by default as identity primary key,
  exchange text not null default 'binance',
  symbol text not null,
  timeframe text not null default 'tick',
  side text not null check (side in ('long', 'short')),
  entry_ts timestamptz not null,
  entry_price numeric not null,
  qty numeric not null,
  tp_price numeric,
  sl_price numeric,
  status text not null default 'open' check (status in ('open', 'closed', 'canceled', 'error')),
  exchange_order_ids jsonb,
  meta jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_trades_symbol_status_entry_ts
  on public.trades (symbol, status, entry_ts desc);

drop trigger if exists trg_trades_updated_at on public.trades;
create trigger trg_trades_updated_at
before update on public.trades
for each row
execute function public.set_updated_at();

create table if not exists public.candles (
  id bigint generated by default as identity primary key,
  exchange text not null,
  symbol text not null,
  timeframe text not null,
  ts timestamptz not null,
  open numeric not null,
  high numeric,
  low numeric,
  close numeric not null,
  volume numeric not null default 0,
  created_at timestamptz not null default now(),
  unique (exchange, symbol, timeframe, ts)
);

create index if not exists idx_candles_lookup
  on public.candles (exchange, symbol, timeframe, ts desc);

create table if not exists public.bot_state (
  exchange text not null,
  symbol text not null,
  timeframe text not null,
  last_ts timestamptz,
  updated_at timestamptz not null default now(),
  primary key (exchange, symbol, timeframe)
);

drop trigger if exists trg_bot_state_updated_at on public.bot_state;
create trigger trg_bot_state_updated_at
before update on public.bot_state
for each row
execute function public.set_updated_at();

create table if not exists public.trading_engine_configs (
  id text primary key,
  config jsonb not null,
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_trading_engine_configs_updated_at on public.trading_engine_configs;
create trigger trg_trading_engine_configs_updated_at
before update on public.trading_engine_configs
for each row
execute function public.set_updated_at();

-- ==========================================
-- 11. Distributed locks and news dedup history
-- ==========================================

create table if not exists public.distributed_locks (
  name text primary key,
  owner_token text,
  expires_at timestamptz,
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_distributed_locks_updated_at on public.distributed_locks;
create trigger trg_distributed_locks_updated_at
before update on public.distributed_locks
for each row
execute function public.set_updated_at();

create table if not exists public.news_sentiment (
  id bigint generated by default as identity primary key,
  guild_id text,
  title text not null,
  link text not null,
  event_signature text,
  sentiment_score numeric,
  created_at timestamptz not null default now()
);

alter table public.news_sentiment add column if not exists guild_id text;
alter table public.news_sentiment add column if not exists title text;
alter table public.news_sentiment add column if not exists link text;
alter table public.news_sentiment add column if not exists event_signature text;
alter table public.news_sentiment add column if not exists sentiment_score numeric;
alter table public.news_sentiment add column if not exists created_at timestamptz not null default now();

create index if not exists idx_news_sentiment_guild_created_at
  on public.news_sentiment (guild_id, created_at desc);

create index if not exists idx_news_sentiment_event_signature
  on public.news_sentiment (event_signature);

-- ==========================================
-- 12. Distributed API rate limiting
-- ==========================================

create table if not exists public.api_rate_limits (
  bucket_key text not null,
  window_start timestamptz not null,
  window_end timestamptz not null,
  hit_count integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key (bucket_key, window_start)
);

create index if not exists idx_api_rate_limits_window_end
  on public.api_rate_limits (window_end);

create or replace function public.acquire_rate_limit(
  p_key text,
  p_window_start timestamptz,
  p_window_end timestamptz,
  p_max integer
)
returns table (
  allowed boolean,
  current_count integer,
  retry_after_sec integer
)
language plpgsql
as $$
declare
  v_count integer;
begin
  insert into public.api_rate_limits (bucket_key, window_start, window_end, hit_count, updated_at)
  values (p_key, p_window_start, p_window_end, 1, now())
  on conflict (bucket_key, window_start)
  do update
    set hit_count = public.api_rate_limits.hit_count + 1,
        window_end = excluded.window_end,
        updated_at = now()
  returning hit_count into v_count;

  allowed := v_count <= greatest(1, p_max);
  current_count := v_count;
  retry_after_sec := greatest(1, ceil(extract(epoch from (p_window_end - now())))::integer);
  return next;
end;
$$;

-- ==========================================
-- 13. Multi-agent sessions and long memory
-- ==========================================

create table if not exists public.guild_lore_docs (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  title text not null,
  summary text,
  content text,
  source text,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists idx_guild_lore_docs_guild_updated_at
  on public.guild_lore_docs (guild_id, updated_at desc);

create table if not exists public.agent_sessions (
  id text primary key,
  guild_id text not null,
  requested_by text not null,
  goal text not null,
  priority text not null default 'balanced',
  requested_skill_id text,
  status text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  started_at timestamptz,
  ended_at timestamptz,
  result text,
  error text
);

create index if not exists idx_agent_sessions_guild_updated_at
  on public.agent_sessions (guild_id, updated_at desc);

alter table if exists public.agent_sessions
  add column if not exists priority text not null default 'balanced';

drop trigger if exists trg_agent_sessions_updated_at on public.agent_sessions;
create trigger trg_agent_sessions_updated_at
before update on public.agent_sessions
for each row
execute function public.set_updated_at();

create table if not exists public.agent_steps (
  id text primary key,
  session_id text not null references public.agent_sessions(id) on delete cascade,
  role text not null,
  title text not null,
  status text not null,
  started_at timestamptz,
  ended_at timestamptz,
  output text,
  error text,
  updated_at timestamptz not null default now()
);

create index if not exists idx_agent_steps_session_updated_at
  on public.agent_steps (session_id, updated_at desc);

drop trigger if exists trg_agent_steps_updated_at on public.agent_steps;
create trigger trg_agent_steps_updated_at
before update on public.agent_steps
for each row
execute function public.set_updated_at();

-- ==========================================
-- 14. Long-term memory agent (guild context)
-- ==========================================

create table if not exists public.memory_items (
  id text primary key,
  guild_id text not null,
  channel_id text,
  scope text not null default 'guild',
  owner_user_id text,
  type text not null,
  title text,
  content text not null,
  summary text,
  tags text[] not null default '{}',
  status text not null default 'active',
  confidence numeric(4, 3) not null default 0.500,
  priority integer not null default 50,
  pinned boolean not null default false,
  source_count integer not null default 0,
  conflict_key text,
  expires_at timestamptz,
  created_by text,
  updated_by text,
  approved_by text,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (scope in ('guild', 'channel', 'user')),
  check (type in ('episode', 'semantic', 'policy', 'preference')),
  check (status in ('active', 'deprecated', 'archived')),
  check (confidence >= 0 and confidence <= 1)
);

create index if not exists idx_memory_items_guild_type_updated
  on public.memory_items (guild_id, type, updated_at desc);

alter table public.memory_items
  add column if not exists owner_user_id text;

create index if not exists idx_memory_items_guild_owner_updated
  on public.memory_items (guild_id, owner_user_id, updated_at desc)
  where owner_user_id is not null;

create index if not exists idx_memory_items_guild_status_priority
  on public.memory_items (guild_id, status, pinned desc, priority desc, updated_at desc);

create index if not exists idx_memory_items_conflict_key
  on public.memory_items (guild_id, conflict_key)
  where conflict_key is not null;

drop trigger if exists trg_memory_items_updated_at on public.memory_items;
create trigger trg_memory_items_updated_at
before update on public.memory_items
for each row
execute function public.set_updated_at();

create table if not exists public.memory_sources (
  id bigint generated by default as identity primary key,
  memory_item_id text not null references public.memory_items(id) on delete cascade,
  guild_id text not null,
  channel_id text,
  source_kind text not null default 'discord_message',
  source_message_id text,
  source_author_id text,
  source_ref text,
  excerpt text,
  source_ts timestamptz,
  created_at timestamptz not null default now(),
  check (source_kind in ('discord_message', 'summary_job', 'admin_edit', 'system'))
);

create index if not exists idx_memory_sources_item_created
  on public.memory_sources (memory_item_id, created_at desc);

create index if not exists idx_memory_sources_guild_message
  on public.memory_sources (guild_id, source_message_id)
  where source_message_id is not null;

create table if not exists public.memory_feedback (
  id bigint generated by default as identity primary key,
  memory_item_id text not null references public.memory_items(id) on delete cascade,
  guild_id text not null,
  action text not null,
  actor_id text not null,
  reason text,
  patch jsonb,
  created_at timestamptz not null default now(),
  check (action in ('pin', 'unpin', 'edit', 'deprecate', 'restore', 'approve', 'reject'))
);

create index if not exists idx_memory_feedback_item_created
  on public.memory_feedback (memory_item_id, created_at desc);

create index if not exists idx_memory_feedback_guild_created
  on public.memory_feedback (guild_id, created_at desc);

create table if not exists public.memory_conflicts (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  conflict_key text not null,
  item_a_id text references public.memory_items(id) on delete set null,
  item_b_id text references public.memory_items(id) on delete set null,
  status text not null default 'open',
  detected_by text not null default 'system',
  resolution text,
  resolved_by text,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (status in ('open', 'resolved', 'ignored'))
);

create index if not exists idx_memory_conflicts_guild_status
  on public.memory_conflicts (guild_id, status, created_at desc);

drop trigger if exists trg_memory_conflicts_updated_at on public.memory_conflicts;
create trigger trg_memory_conflicts_updated_at
before update on public.memory_conflicts
for each row
execute function public.set_updated_at();

create table if not exists public.memory_jobs (
  id text primary key,
  guild_id text not null,
  job_type text not null,
  status text not null default 'queued',
  next_attempt_at timestamptz not null default now(),
  window_started_at timestamptz,
  window_ended_at timestamptz,
  input jsonb,
  output jsonb,
  error text,
  deadlettered_at timestamptz,
  deadletter_reason text,
  attempts integer not null default 0,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (job_type in ('short_summary', 'topic_synthesis', 'durable_extraction', 'reindex', 'conflict_scan', 'onboarding_snapshot')),
  check (status in ('queued', 'running', 'completed', 'failed', 'canceled'))
);

create index if not exists idx_memory_jobs_guild_status_created
  on public.memory_jobs (guild_id, status, created_at desc);

create index if not exists idx_memory_jobs_type_status
  on public.memory_jobs (job_type, status, created_at desc);

create index if not exists idx_memory_jobs_status_next_attempt
  on public.memory_jobs (status, next_attempt_at asc)
  where status = 'queued';

alter table public.memory_jobs add column if not exists next_attempt_at timestamptz;
alter table public.memory_jobs add column if not exists deadlettered_at timestamptz;
alter table public.memory_jobs add column if not exists deadletter_reason text;

update public.memory_jobs
set next_attempt_at = coalesce(next_attempt_at, created_at, now())
where next_attempt_at is null;

alter table public.memory_jobs alter column next_attempt_at set default now();
alter table public.memory_jobs alter column next_attempt_at set not null;

create table if not exists public.memory_job_deadletters (
  id bigint generated by default as identity primary key,
  job_id text,
  guild_id text not null,
  job_type text not null,
  attempts integer not null,
  error text not null,
  input jsonb,
  output jsonb,
  recovery_status text not null default 'pending',
  recovery_attempts integer not null default 0,
  recovered_at timestamptz,
  last_recovery_error text,
  failed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (job_type in ('short_summary', 'topic_synthesis', 'durable_extraction', 'reindex', 'conflict_scan', 'onboarding_snapshot')),
  check (recovery_status in ('pending', 'requeued', 'ignored')),
  check (recovery_attempts >= 0)
);

create index if not exists idx_memory_job_deadletters_guild_created
  on public.memory_job_deadletters (guild_id, created_at desc);

create index if not exists idx_memory_job_deadletters_job_id
  on public.memory_job_deadletters (job_id);

create index if not exists idx_memory_job_deadletters_recovery
  on public.memory_job_deadletters (recovery_status, created_at desc);

alter table public.memory_job_deadletters add column if not exists recovery_status text;
alter table public.memory_job_deadletters add column if not exists recovery_attempts integer;
alter table public.memory_job_deadletters add column if not exists recovered_at timestamptz;
alter table public.memory_job_deadletters add column if not exists last_recovery_error text;
alter table public.memory_job_deadletters add column if not exists updated_at timestamptz;

update public.memory_job_deadletters
set recovery_status = coalesce(recovery_status, 'pending')
where recovery_status is null;

update public.memory_job_deadletters
set recovery_attempts = coalesce(recovery_attempts, 0)
where recovery_attempts is null;

update public.memory_job_deadletters
set updated_at = coalesce(updated_at, created_at, now())
where updated_at is null;

alter table public.memory_job_deadletters alter column recovery_status set default 'pending';
alter table public.memory_job_deadletters alter column recovery_status set not null;
alter table public.memory_job_deadletters alter column recovery_attempts set default 0;
alter table public.memory_job_deadletters alter column recovery_attempts set not null;
alter table public.memory_job_deadletters alter column updated_at set default now();
alter table public.memory_job_deadletters alter column updated_at set not null;

drop trigger if exists trg_memory_job_deadletters_updated_at on public.memory_job_deadletters;
create trigger trg_memory_job_deadletters_updated_at
before update on public.memory_job_deadletters
for each row
execute function public.set_updated_at();

create table if not exists public.memory_retrieval_logs (
  id text primary key,
  guild_id text not null,
  query text not null,
  query_type text,
  requested_top_k integer not null default 8,
  returned_count integer not null default 0,
  query_latency_ms integer not null default 0,
  avg_score numeric(5, 4) not null default 0,
  avg_citations numeric(5, 2) not null default 0,
  created_at timestamptz not null default now(),
  check (requested_top_k >= 1 and requested_top_k <= 50),
  check (returned_count >= 0),
  check (query_latency_ms >= 0),
  check (avg_score >= 0 and avg_score <= 1),
  check (avg_citations >= 0)
);

create index if not exists idx_memory_retrieval_logs_guild_created
  on public.memory_retrieval_logs (guild_id, created_at desc);

create index if not exists idx_memory_retrieval_logs_created
  on public.memory_retrieval_logs (created_at desc);

create table if not exists public.agent_action_logs (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  requested_by text not null,
  goal text not null,
  action_name text not null,
  status text not null default 'success',
  summary text,
  artifacts jsonb not null default '[]'::jsonb,
  verification jsonb not null default '[]'::jsonb,
  duration_ms integer not null default 0,
  retry_count integer not null default 0,
  circuit_open boolean not null default false,
  estimated_cost_usd numeric(12, 6),
  finops_mode text,
  error text,
  created_at timestamptz not null default now(),
  check (status in ('success', 'failed')),
  check (duration_ms >= 0),
  check (retry_count >= 0),
  check (estimated_cost_usd is null or estimated_cost_usd >= 0),
  check (finops_mode is null or finops_mode in ('normal', 'degraded', 'blocked'))
);

alter table public.agent_action_logs add column if not exists estimated_cost_usd numeric(12, 6);
alter table public.agent_action_logs add column if not exists finops_mode text;

create index if not exists idx_agent_action_logs_guild_created
  on public.agent_action_logs (guild_id, created_at desc);

create index if not exists idx_agent_action_logs_action_created
  on public.agent_action_logs (action_name, created_at desc);

-- ==========================================
-- 15. RLS policies for memory domain
-- ==========================================

alter table public.memory_items enable row level security;
alter table public.memory_sources enable row level security;
alter table public.memory_feedback enable row level security;
alter table public.memory_conflicts enable row level security;
alter table public.memory_jobs enable row level security;
alter table public.memory_job_deadletters enable row level security;
alter table public.memory_retrieval_logs enable row level security;
alter table public.agent_action_logs enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='memory_items' and policyname='memory_items_guild_select'
  ) then
    create policy memory_items_guild_select on public.memory_items
      for select
      using (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='memory_items' and policyname='memory_items_guild_write'
  ) then
    create policy memory_items_guild_write on public.memory_items
      for all
      using (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''))
      with check (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='memory_sources' and policyname='memory_sources_guild_all'
  ) then
    create policy memory_sources_guild_all on public.memory_sources
      for all
      using (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''))
      with check (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='memory_feedback' and policyname='memory_feedback_guild_all'
  ) then
    create policy memory_feedback_guild_all on public.memory_feedback
      for all
      using (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''))
      with check (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='memory_conflicts' and policyname='memory_conflicts_guild_all'
  ) then
    create policy memory_conflicts_guild_all on public.memory_conflicts
      for all
      using (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''))
      with check (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='memory_jobs' and policyname='memory_jobs_guild_all'
  ) then
    create policy memory_jobs_guild_all on public.memory_jobs
      for all
      using (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''))
      with check (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='memory_job_deadletters' and policyname='memory_deadletters_guild_all'
  ) then
    create policy memory_deadletters_guild_all on public.memory_job_deadletters
      for all
      using (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''))
      with check (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='memory_retrieval_logs' and policyname='memory_retrieval_logs_guild_all'
  ) then
    create policy memory_retrieval_logs_guild_all on public.memory_retrieval_logs
      for all
      using (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''))
      with check (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='agent_action_logs' and policyname='agent_action_logs_guild_all'
  ) then
    create policy agent_action_logs_guild_all on public.agent_action_logs
      for all
      using (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''))
      with check (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;
end
$$;

drop trigger if exists trg_memory_jobs_updated_at on public.memory_jobs;
create trigger trg_memory_jobs_updated_at
before update on public.memory_jobs
for each row
execute function public.set_updated_at();

-- ==========================================
-- 16. Tenant action governance
-- ==========================================

create table if not exists public.agent_action_policies (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  action_name text not null,
  enabled boolean not null default true,
  run_mode text not null default 'auto',
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (guild_id, action_name),
  check (run_mode in ('auto', 'approval_required', 'disabled'))
);

create index if not exists idx_agent_action_policies_guild_action
  on public.agent_action_policies (guild_id, action_name);

drop trigger if exists trg_agent_action_policies_updated_at on public.agent_action_policies;
create trigger trg_agent_action_policies_updated_at
before update on public.agent_action_policies
for each row
execute function public.set_updated_at();

create table if not exists public.agent_action_approval_requests (
  id text primary key,
  guild_id text not null,
  requested_by text not null,
  goal text not null,
  action_name text not null,
  action_args jsonb not null default '{}'::jsonb,
  status text not null default 'pending',
  reason text,
  approved_by text,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  check (status in ('pending', 'approved', 'rejected', 'expired'))
);

create index if not exists idx_agent_action_approvals_guild_created
  on public.agent_action_approval_requests (guild_id, created_at desc);

create index if not exists idx_agent_action_approvals_status_expires
  on public.agent_action_approval_requests (status, expires_at asc);

alter table public.agent_action_policies enable row level security;
alter table public.agent_action_approval_requests enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='agent_action_policies' and policyname='agent_action_policies_guild_all'
  ) then
    create policy agent_action_policies_guild_all on public.agent_action_policies
      for all
      using (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''))
      with check (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='agent_action_approval_requests' and policyname='agent_action_approvals_guild_all'
  ) then
    create policy agent_action_approvals_guild_all on public.agent_action_approval_requests
      for all
      using (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''))
      with check (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;
end
$$;
