-- Supabase schema bootstrap (idempotent)
-- Run in Supabase SQL Editor.

-- ==========================================
-- 1. Initial reset (optional)
-- ==========================================
-- drop table if exists public.error_history cascade;
-- drop table if exists public.macro_data cascade;
-- drop table if exists public.macro_series cascade;
-- drop table if exists public.logs cascade;
-- drop table if exists public.settings cascade;
-- drop table if exists public.alert_slots cascade;
-- drop table if exists public.sources cascade;
-- drop table if exists public.users cascade;

-- ==========================================
-- 2. User and service infrastructure
-- ==========================================

create table if not exists public.users (
  id text primary key,
  username text not null,
  avatar text,
  discord_access_token text,
  discord_refresh_token text,
  created_at timestamptz default current_timestamp,
  updated_at timestamptz default current_timestamp
);

create table if not exists public.sources (
  id serial primary key,
  user_id text references public.users(id) on delete set null,
  name text not null,
  url text not null unique,
  guild_id text,
  channel_id text,
  guild_name text,
  channel_name text,
  is_active boolean not null default true,
  lock_token text,
  lock_expires_at timestamptz,
  last_post_id text,
  last_post_signature text,
  last_check_status text,
  last_check_error text,
  last_check_at timestamptz,
  created_at timestamptz default current_timestamp
);

-- Node-only migration safety: add columns when table already exists from older schema.
alter table public.sources add column if not exists guild_id text;
alter table public.sources add column if not exists channel_id text;
alter table public.sources add column if not exists guild_name text;
alter table public.sources add column if not exists channel_name text;
alter table public.sources add column if not exists is_active boolean not null default true;
alter table public.sources add column if not exists lock_token text;
alter table public.sources add column if not exists lock_expires_at timestamptz;

create index if not exists idx_sources_guild_channel on public.sources (guild_id, channel_id);
create index if not exists idx_sources_lock on public.sources (lock_token, lock_expires_at);

create table if not exists public.alert_slots (
  id serial primary key,
  user_id text not null references public.users(id) on delete cascade,
  source_id int not null references public.sources(id) on delete cascade,
  guild_id text not null,
  channel_id text not null,
  guild_name text,
  channel_name text,
  is_active boolean default true,
  created_at timestamptz default current_timestamp,
  unique(source_id, channel_id)
);

create table if not exists public.settings (
  key text,
  user_id text references public.users(id) on delete cascade,
  value text not null,
  updated_at timestamptz default current_timestamp,
  primary key (key, user_id)
);

create table if not exists public.logs (
  id serial primary key,
  user_id text references public.users(id) on delete cascade,
  message text not null,
  type text not null,
  created_at timestamptz default current_timestamp
);

-- ==========================================
-- 3. Macro indicator infrastructure
-- ==========================================

create table if not exists public.macro_series (
  series_id text primary key,
  name text not null,
  frequency text,
  description text,
  last_updated timestamptz default now()
);

create table if not exists public.macro_data (
  id serial primary key,
  series_id text references public.macro_series(series_id) on delete cascade,
  date date not null,
  value numeric not null,
  created_at timestamptz default now(),
  unique(series_id, date)
);

insert into public.macro_series (series_id, name, frequency, description) values
('CPIAUCSL', 'Consumer Price Index (CPI)', 'Monthly', 'US urban consumer price index'),
('FEDFUNDS', 'Federal Funds Rate', 'Monthly', 'US central bank policy rate'),
('T10Y2Y', 'Yield Spread (10Y-2Y)', 'Daily', 'Treasury curve inversion indicator'),
('M2SL', 'M2 Money Stock', 'Monthly', 'Broad money supply')
on conflict (series_id) do update
set name = excluded.name,
    frequency = excluded.frequency,
    description = excluded.description;

-- ==========================================
-- 4. Error logging optimization
-- ==========================================

create table if not exists public.error_history (
  id serial primary key,
  source_id int references public.sources(id) on delete cascade,
  error_message text not null,
  occurred_at timestamptz default now()
);

create table if not exists public.system_error_events (
  id bigint generated by default as identity primary key,
  code text not null,
  source text not null,
  severity text not null default 'error',
  message text not null,
  stack text,
  guild_id text,
  session_id text,
  action_name text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_system_error_events_created_at
  on public.system_error_events (created_at desc);

create index if not exists idx_system_error_events_code
  on public.system_error_events (code, created_at desc);

create index if not exists idx_system_error_events_guild
  on public.system_error_events (guild_id, created_at desc);

create or replace function public.log_source_error()
returns trigger
language plpgsql
as $$
begin
  if (new.last_check_status = 'error' and old.last_check_status is distinct from 'error') then
    insert into public.error_history (source_id, error_message)
    values (new.id, new.last_check_error);
  end if;
  return new;
end;
$$;

drop trigger if exists trigger_log_error on public.sources;
create trigger trigger_log_error
after update on public.sources
for each row
execute function public.log_source_error();

-- ==========================================
-- 5. Orphan source cleanup trigger
-- ==========================================

create or replace function public.delete_orphaned_source()
returns trigger
language plpgsql
as $$
begin
  if not exists (select 1 from public.alert_slots where source_id = old.source_id) then
    delete from public.sources where id = old.source_id;
  end if;
  return old;
end;
$$;

drop trigger if exists trigger_delete_orphaned_source on public.alert_slots;
create trigger trigger_delete_orphaned_source
after delete on public.alert_slots
for each row
execute function public.delete_orphaned_source();

-- ==========================================
-- 6. TradingView signal pipeline
-- ==========================================

create table if not exists public.trading_signals (
  id serial primary key,
  symbol text not null,
  signal_type text not null,
  price numeric,
  qty numeric,
  leverage int default 1,
  received_at timestamptz default now()
);

-- ==========================================
-- 7. Quant regime master
-- ==========================================

create table if not exists public.market_regime (
  date date primary key,
  regime_phase text not null,
  inflation_score numeric,
  growth_score numeric,
  description text,
  updated_at timestamptz default now()
);

-- ==========================================
-- 8. User roles
-- ==========================================

create table if not exists public.user_roles (
  user_id text primary key,
  role text not null default 'user',
  granted_at timestamptz default current_timestamp,
  granted_by text
);

create index if not exists idx_user_roles_role on public.user_roles(role);

create table if not exists public.discord_login_sessions (
  guild_id text not null,
  user_id text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (guild_id, user_id)
);

create index if not exists idx_discord_login_sessions_expires_at
  on public.discord_login_sessions (expires_at);

-- Replace with real Discord user id before production use.
insert into public.user_roles (user_id, role)
values ('123456789012345678', 'admin')
on conflict (user_id) do update
set role = 'admin';

-- ==========================================
-- 9. Common updated_at trigger helper
-- ==========================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_discord_login_sessions_updated_at on public.discord_login_sessions;
create trigger trg_discord_login_sessions_updated_at
before update on public.discord_login_sessions
for each row
execute function public.set_updated_at();

-- ==========================================
-- 10. Trading backend runtime tables
-- ==========================================

create table if not exists public.trades (
  id bigint generated by default as identity primary key,
  exchange text not null default 'binance',
  symbol text not null,
  timeframe text not null default 'tick',
  side text not null check (side in ('long', 'short')),
  entry_ts timestamptz not null,
  entry_price numeric not null,
  qty numeric not null,
  tp_price numeric,
  sl_price numeric,
  status text not null default 'open' check (status in ('open', 'closed', 'canceled', 'error')),
  exchange_order_ids jsonb,
  meta jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_trades_symbol_status_entry_ts
  on public.trades (symbol, status, entry_ts desc);

drop trigger if exists trg_trades_updated_at on public.trades;
create trigger trg_trades_updated_at
before update on public.trades
for each row
execute function public.set_updated_at();

create table if not exists public.candles (
  id bigint generated by default as identity primary key,
  exchange text not null,
  symbol text not null,
  timeframe text not null,
  ts timestamptz not null,
  open numeric not null,
  high numeric,
  low numeric,
  close numeric not null,
  volume numeric not null default 0,
  created_at timestamptz not null default now(),
  unique (exchange, symbol, timeframe, ts)
);

create index if not exists idx_candles_lookup
  on public.candles (exchange, symbol, timeframe, ts desc);

create table if not exists public.bot_state (
  exchange text not null,
  symbol text not null,
  timeframe text not null,
  last_ts timestamptz,
  updated_at timestamptz not null default now(),
  primary key (exchange, symbol, timeframe)
);

drop trigger if exists trg_bot_state_updated_at on public.bot_state;
create trigger trg_bot_state_updated_at
before update on public.bot_state
for each row
execute function public.set_updated_at();

create table if not exists public.trading_engine_configs (
  id text primary key,
  config jsonb not null,
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_trading_engine_configs_updated_at on public.trading_engine_configs;
create trigger trg_trading_engine_configs_updated_at
before update on public.trading_engine_configs
for each row
execute function public.set_updated_at();

-- ==========================================
-- 11. Distributed locks and news dedup history
-- ==========================================

create table if not exists public.distributed_locks (
  name text primary key,
  owner_token text,
  expires_at timestamptz,
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_distributed_locks_updated_at on public.distributed_locks;
create trigger trg_distributed_locks_updated_at
before update on public.distributed_locks
for each row
execute function public.set_updated_at();

create table if not exists public.news_sentiment (
  id bigint generated by default as identity primary key,
  guild_id text,
  title text not null,
  link text not null,
  event_signature text,
  sentiment_score numeric,
  created_at timestamptz not null default now()
);

alter table public.news_sentiment add column if not exists guild_id text;
alter table public.news_sentiment add column if not exists title text;
alter table public.news_sentiment add column if not exists link text;
alter table public.news_sentiment add column if not exists event_signature text;
alter table public.news_sentiment add column if not exists sentiment_score numeric;
alter table public.news_sentiment add column if not exists created_at timestamptz not null default now();

create index if not exists idx_news_sentiment_guild_created_at
  on public.news_sentiment (guild_id, created_at desc);

create index if not exists idx_news_sentiment_event_signature
  on public.news_sentiment (event_signature);

-- ==========================================
-- 12. Distributed API rate limiting
-- ==========================================

create table if not exists public.api_rate_limits (
  bucket_key text not null,
  window_start timestamptz not null,
  window_end timestamptz not null,
  hit_count integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key (bucket_key, window_start)
);

create index if not exists idx_api_rate_limits_window_end
  on public.api_rate_limits (window_end);

create or replace function public.acquire_rate_limit(
  p_key text,
  p_window_start timestamptz,
  p_window_end timestamptz,
  p_max integer
)
returns table (
  allowed boolean,
  current_count integer,
  retry_after_sec integer
)
language plpgsql
as $$
declare
  v_count integer;
begin
  insert into public.api_rate_limits (bucket_key, window_start, window_end, hit_count, updated_at)
  values (p_key, p_window_start, p_window_end, 1, now())
  on conflict (bucket_key, window_start)
  do update
    set hit_count = public.api_rate_limits.hit_count + 1,
        window_end = excluded.window_end,
        updated_at = now()
  returning hit_count into v_count;

  allowed := v_count <= greatest(1, p_max);
  current_count := v_count;
  retry_after_sec := greatest(1, ceil(extract(epoch from (p_window_end - now())))::integer);
  return next;
end;
$$;

-- ==========================================
-- 13. Multi-agent sessions and long memory
-- ==========================================

create table if not exists public.guild_lore_docs (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  title text not null,
  summary text,
  content text,
  source text,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists idx_guild_lore_docs_guild_updated_at
  on public.guild_lore_docs (guild_id, updated_at desc);

create table if not exists public.agent_sessions (
  id text primary key,
  guild_id text not null,
  requested_by text not null,
  goal text not null,
  priority text not null default 'balanced',
  requested_skill_id text,
  status text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  started_at timestamptz,
  ended_at timestamptz,
  result text,
  error text,
  shadow_graph_summary jsonb,
  progress_summary jsonb
);

create index if not exists idx_agent_sessions_guild_updated_at
  on public.agent_sessions (guild_id, updated_at desc);

alter table if exists public.agent_sessions
  add column if not exists priority text not null default 'balanced';

alter table if exists public.agent_sessions
  add column if not exists shadow_graph_summary jsonb;

alter table if exists public.agent_sessions
  add column if not exists progress_summary jsonb;

drop trigger if exists trg_agent_sessions_updated_at on public.agent_sessions;
create trigger trg_agent_sessions_updated_at
before update on public.agent_sessions
for each row
execute function public.set_updated_at();

create table if not exists public.agent_steps (
  id text primary key,
  session_id text not null references public.agent_sessions(id) on delete cascade,
  role text not null,
  title text not null,
  status text not null,
  started_at timestamptz,
  ended_at timestamptz,
  output text,
  error text,
  updated_at timestamptz not null default now()
);

create index if not exists idx_agent_steps_session_updated_at
  on public.agent_steps (session_id, updated_at desc);

drop trigger if exists trg_agent_steps_updated_at on public.agent_steps;
create trigger trg_agent_steps_updated_at
before update on public.agent_steps
for each row
execute function public.set_updated_at();

-- ==========================================
-- 14. Long-term memory agent (guild context)
-- ==========================================

create table if not exists public.memory_items (
  id text primary key,
  guild_id text not null,
  channel_id text,
  scope text not null default 'guild',
  owner_user_id text,
  type text not null,
  title text,
  content text not null,
  summary text,
  tags text[] not null default '{}',
  status text not null default 'active',
  confidence numeric(4, 3) not null default 0.500,
  priority integer not null default 50,
  pinned boolean not null default false,
  source_count integer not null default 0,
  conflict_key text,
  expires_at timestamptz,
  created_by text,
  updated_by text,
  approved_by text,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (scope in ('guild', 'channel', 'user')),
  check (type in ('episode', 'semantic', 'policy', 'preference')),
  check (status in ('active', 'deprecated', 'archived')),
  check (confidence >= 0 and confidence <= 1)
);

create index if not exists idx_memory_items_guild_type_updated
  on public.memory_items (guild_id, type, updated_at desc);

alter table public.memory_items
  add column if not exists owner_user_id text;

create index if not exists idx_memory_items_guild_owner_updated
  on public.memory_items (guild_id, owner_user_id, updated_at desc)
  where owner_user_id is not null;

create index if not exists idx_memory_items_guild_status_priority
  on public.memory_items (guild_id, status, pinned desc, priority desc, updated_at desc);

create index if not exists idx_memory_items_conflict_key
  on public.memory_items (guild_id, conflict_key)
  where conflict_key is not null;

drop trigger if exists trg_memory_items_updated_at on public.memory_items;
create trigger trg_memory_items_updated_at
before update on public.memory_items
for each row
execute function public.set_updated_at();

create table if not exists public.memory_sources (
  id bigint generated by default as identity primary key,
  memory_item_id text not null references public.memory_items(id) on delete cascade,
  guild_id text not null,
  channel_id text,
  source_kind text not null default 'discord_message',
  source_message_id text,
  source_author_id text,
  source_ref text,
  excerpt text,
  source_ts timestamptz,
  created_at timestamptz not null default now(),
  check (source_kind in ('discord_message', 'summary_job', 'admin_edit', 'system'))
);

create index if not exists idx_memory_sources_item_created
  on public.memory_sources (memory_item_id, created_at desc);

create index if not exists idx_memory_sources_guild_message
  on public.memory_sources (guild_id, source_message_id)
  where source_message_id is not null;

create table if not exists public.memory_feedback (
  id bigint generated by default as identity primary key,
  memory_item_id text not null references public.memory_items(id) on delete cascade,
  guild_id text not null,
  action text not null,
  actor_id text not null,
  reason text,
  patch jsonb,
  created_at timestamptz not null default now(),
  check (action in ('pin', 'unpin', 'edit', 'deprecate', 'restore', 'approve', 'reject'))
);

create index if not exists idx_memory_feedback_item_created
  on public.memory_feedback (memory_item_id, created_at desc);

create index if not exists idx_memory_feedback_guild_created
  on public.memory_feedback (guild_id, created_at desc);

create table if not exists public.memory_conflicts (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  conflict_key text not null,
  item_a_id text references public.memory_items(id) on delete set null,
  item_b_id text references public.memory_items(id) on delete set null,
  status text not null default 'open',
  detected_by text not null default 'system',
  resolution text,
  resolved_by text,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (status in ('open', 'resolved', 'ignored'))
);

create index if not exists idx_memory_conflicts_guild_status
  on public.memory_conflicts (guild_id, status, created_at desc);

drop trigger if exists trg_memory_conflicts_updated_at on public.memory_conflicts;
create trigger trg_memory_conflicts_updated_at
before update on public.memory_conflicts
for each row
execute function public.set_updated_at();

create table if not exists public.memory_jobs (
  id text primary key,
  guild_id text not null,
  job_type text not null,
  status text not null default 'queued',
  next_attempt_at timestamptz not null default now(),
  window_started_at timestamptz,
  window_ended_at timestamptz,
  input jsonb,
  output jsonb,
  error text,
  deadlettered_at timestamptz,
  deadletter_reason text,
  attempts integer not null default 0,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (job_type in ('short_summary', 'topic_synthesis', 'durable_extraction', 'reindex', 'conflict_scan', 'onboarding_snapshot')),
  check (status in ('queued', 'running', 'completed', 'failed', 'canceled'))
);

create index if not exists idx_memory_jobs_guild_status_created
  on public.memory_jobs (guild_id, status, created_at desc);

create index if not exists idx_memory_jobs_type_status
  on public.memory_jobs (job_type, status, created_at desc);

create index if not exists idx_memory_jobs_status_next_attempt
  on public.memory_jobs (status, next_attempt_at asc)
  where status = 'queued';

alter table public.memory_jobs add column if not exists next_attempt_at timestamptz;
alter table public.memory_jobs add column if not exists deadlettered_at timestamptz;
alter table public.memory_jobs add column if not exists deadletter_reason text;

update public.memory_jobs
set next_attempt_at = coalesce(next_attempt_at, created_at, now())
where next_attempt_at is null;

alter table public.memory_jobs alter column next_attempt_at set default now();
alter table public.memory_jobs alter column next_attempt_at set not null;

create table if not exists public.memory_job_deadletters (
  id bigint generated by default as identity primary key,
  job_id text,
  guild_id text not null,
  job_type text not null,
  attempts integer not null,
  error text not null,
  input jsonb,
  output jsonb,
  recovery_status text not null default 'pending',
  recovery_attempts integer not null default 0,
  recovered_at timestamptz,
  last_recovery_error text,
  failed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (job_type in ('short_summary', 'topic_synthesis', 'durable_extraction', 'reindex', 'conflict_scan', 'onboarding_snapshot')),
  check (recovery_status in ('pending', 'requeued', 'ignored')),
  check (recovery_attempts >= 0)
);

create index if not exists idx_memory_job_deadletters_guild_created
  on public.memory_job_deadletters (guild_id, created_at desc);

create index if not exists idx_memory_job_deadletters_job_id
  on public.memory_job_deadletters (job_id);

create index if not exists idx_memory_job_deadletters_recovery
  on public.memory_job_deadletters (recovery_status, created_at desc);

alter table public.memory_job_deadletters add column if not exists recovery_status text;
alter table public.memory_job_deadletters add column if not exists recovery_attempts integer;
alter table public.memory_job_deadletters add column if not exists recovered_at timestamptz;
alter table public.memory_job_deadletters add column if not exists last_recovery_error text;
alter table public.memory_job_deadletters add column if not exists updated_at timestamptz;

update public.memory_job_deadletters
set recovery_status = coalesce(recovery_status, 'pending')
where recovery_status is null;

update public.memory_job_deadletters
set recovery_attempts = coalesce(recovery_attempts, 0)
where recovery_attempts is null;

update public.memory_job_deadletters
set updated_at = coalesce(updated_at, created_at, now())
where updated_at is null;

alter table public.memory_job_deadletters alter column recovery_status set default 'pending';
alter table public.memory_job_deadletters alter column recovery_status set not null;
alter table public.memory_job_deadletters alter column recovery_attempts set default 0;
alter table public.memory_job_deadletters alter column recovery_attempts set not null;
alter table public.memory_job_deadletters alter column updated_at set default now();
alter table public.memory_job_deadletters alter column updated_at set not null;

drop trigger if exists trg_memory_job_deadletters_updated_at on public.memory_job_deadletters;
create trigger trg_memory_job_deadletters_updated_at
before update on public.memory_job_deadletters
for each row
execute function public.set_updated_at();

create table if not exists public.memory_retrieval_logs (
  id text primary key,
  guild_id text not null,
  query text not null,
  query_type text,
  requested_top_k integer not null default 8,
  returned_count integer not null default 0,
  query_latency_ms integer not null default 0,
  avg_score numeric(5, 4) not null default 0,
  avg_citations numeric(5, 2) not null default 0,
  created_at timestamptz not null default now(),
  check (requested_top_k >= 1 and requested_top_k <= 50),
  check (returned_count >= 0),
  check (query_latency_ms >= 0),
  check (avg_score >= 0 and avg_score <= 1),
  check (avg_citations >= 0)
);

create index if not exists idx_memory_retrieval_logs_guild_created
  on public.memory_retrieval_logs (guild_id, created_at desc);

create index if not exists idx_memory_retrieval_logs_created
  on public.memory_retrieval_logs (created_at desc);

create table if not exists public.agent_action_logs (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  requested_by text not null,
  goal text not null,
  action_name text not null,
  status text not null default 'success',
  summary text,
  artifacts jsonb not null default '[]'::jsonb,
  verification jsonb not null default '[]'::jsonb,
  duration_ms integer not null default 0,
  retry_count integer not null default 0,
  circuit_open boolean not null default false,
  estimated_cost_usd numeric(12, 6),
  finops_mode text,
  error text,
  created_at timestamptz not null default now(),
  check (status in ('success', 'failed')),
  check (duration_ms >= 0),
  check (retry_count >= 0),
  check (estimated_cost_usd is null or estimated_cost_usd >= 0),
  check (finops_mode is null or finops_mode in ('normal', 'degraded', 'blocked'))
);

alter table public.agent_action_logs add column if not exists estimated_cost_usd numeric(12, 6);
alter table public.agent_action_logs add column if not exists finops_mode text;

create index if not exists idx_agent_action_logs_guild_created
  on public.agent_action_logs (guild_id, created_at desc);

create index if not exists idx_agent_action_logs_action_created
  on public.agent_action_logs (action_name, created_at desc);

-- ==========================================
-- 15. RLS policies for memory domain
-- ==========================================

alter table public.memory_items enable row level security;
alter table public.memory_sources enable row level security;
alter table public.memory_feedback enable row level security;
alter table public.memory_conflicts enable row level security;
alter table public.memory_jobs enable row level security;
alter table public.memory_job_deadletters enable row level security;
alter table public.memory_retrieval_logs enable row level security;
alter table public.agent_action_logs enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='memory_items' and policyname='memory_items_guild_select'
  ) then
    create policy memory_items_guild_select on public.memory_items
      for select
      using (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='memory_items' and policyname='memory_items_guild_write'
  ) then
    create policy memory_items_guild_write on public.memory_items
      for all
      using (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''))
      with check (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='memory_sources' and policyname='memory_sources_guild_all'
  ) then
    create policy memory_sources_guild_all on public.memory_sources
      for all
      using (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''))
      with check (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='memory_feedback' and policyname='memory_feedback_guild_all'
  ) then
    create policy memory_feedback_guild_all on public.memory_feedback
      for all
      using (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''))
      with check (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='memory_conflicts' and policyname='memory_conflicts_guild_all'
  ) then
    create policy memory_conflicts_guild_all on public.memory_conflicts
      for all
      using (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''))
      with check (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='memory_jobs' and policyname='memory_jobs_guild_all'
  ) then
    create policy memory_jobs_guild_all on public.memory_jobs
      for all
      using (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''))
      with check (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='memory_job_deadletters' and policyname='memory_deadletters_guild_all'
  ) then
    create policy memory_deadletters_guild_all on public.memory_job_deadletters
      for all
      using (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''))
      with check (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='memory_retrieval_logs' and policyname='memory_retrieval_logs_guild_all'
  ) then
    create policy memory_retrieval_logs_guild_all on public.memory_retrieval_logs
      for all
      using (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''))
      with check (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='agent_action_logs' and policyname='agent_action_logs_guild_all'
  ) then
    create policy agent_action_logs_guild_all on public.agent_action_logs
      for all
      using (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''))
      with check (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;
end
$$;

-- ==========================================
-- 19. Agent runtime config (de-hardcoding)
-- ==========================================

create table if not exists public.agent_runtime_policies (
  guild_id text primary key,
  enabled boolean not null default true,
  max_concurrent_sessions integer not null default 4,
  max_goal_length integer not null default 1200,
  restricted_skills text[] not null default '{}',
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (max_concurrent_sessions >= 1),
  check (max_goal_length >= 40)
);

create index if not exists idx_agent_runtime_policies_enabled
  on public.agent_runtime_policies (enabled, updated_at desc);

drop trigger if exists trg_agent_runtime_policies_updated_at on public.agent_runtime_policies;
create trigger trg_agent_runtime_policies_updated_at
before update on public.agent_runtime_policies
for each row
execute function public.set_updated_at();

insert into public.agent_runtime_policies (guild_id, enabled, max_concurrent_sessions, max_goal_length, restricted_skills)
values ('*', true, 4, 1200, '{}')
on conflict (guild_id) do nothing;

create table if not exists public.agent_skill_catalog (
  guild_id text not null default '*',
  skill_id text not null,
  enabled boolean not null default true,
  title text not null,
  description text not null,
  input_guide text not null,
  output_guide text not null,
  system_prompt text not null,
  executor_key text not null,
  admin_only boolean not null default false,
  temperature numeric(4, 3),
  max_tokens integer,
  sort_order integer not null default 100,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (guild_id, skill_id),
  check (max_tokens is null or max_tokens >= 32),
  check (temperature is null or (temperature >= 0 and temperature <= 2))
);

create index if not exists idx_agent_skill_catalog_enabled
  on public.agent_skill_catalog (guild_id, enabled, sort_order asc, updated_at desc);

drop trigger if exists trg_agent_skill_catalog_updated_at on public.agent_skill_catalog;
create trigger trg_agent_skill_catalog_updated_at
before update on public.agent_skill_catalog
for each row
execute function public.set_updated_at();

insert into public.agent_skill_catalog (
  guild_id, skill_id, enabled, title, description, input_guide, output_guide, system_prompt, executor_key, admin_only, temperature, max_tokens, sort_order
) values
  ('*', 'casual_chat', true, '일상 대화 응답', '감정 표현/잡담 입력을 공감형 자연어로 응답합니다.', '감정 표현, 안부, 짧은 일상 발화', '도구 없이 공감 + 필요 시 1개 되묻기', '너는 공감형 한국어 대화 파트너다.', 'casual_chat', false, 0.5, 220, 10),
  ('*', 'ops-plan', true, '운영 계획 수립', '목표를 실행 가능한 단계로 분해하고 우선순위를 제안합니다.', '운영 목표, 제한사항, 기간, 성공조건', '단계별 실행계획 + 실패시 대안 + 우선순위', '너는 디스코드 서버 운영 자동화 계획가다.', 'ops-plan', false, 0.2, 900, 20),
  ('*', 'ops-execution', true, '운영 실행안 생성', '계획을 실제 운영자가 사용할 수 있는 체크리스트로 변환합니다.', '목표 + 계획안 + 리소스 제약', '즉시 실행 체크리스트 + 자동화 포인트 + 관찰 지표', '너는 서버 운영 실행 담당 에이전트다.', 'ops-execution', false, 0.25, 1000, 30),
  ('*', 'ops-critique', true, '운영 리스크 검토', '실행안의 리스크와 보완책을 검토합니다.', '목표 + 실행안', '리스크 목록 + 완화안 + 즉시 적용 가드레일', '너는 운영 품질/보안 검토 에이전트다.', 'ops-critique', false, 0.1, 800, 40),
  ('*', 'guild-onboarding-blueprint', true, '길드 온보딩 설계', '서버 초대 후 온보딩 절차와 동의 기반 학습 플로우를 설계합니다.', '서버 성격, 권한 정책, 수집 범위', '온보딩 상태머신 + 동의 UX + 초기 데이터 수집 전략', '너는 디스코드 길드 온보딩 아키텍트다.', 'guild-onboarding-blueprint', false, 0.2, 1200, 50),
  ('*', 'incident-review', true, '장애/오답 회고', '장애나 오답 사례를 회고하고 재발 방지 규칙을 도출합니다.', '사건 요약, 영향, 현재 대응', '원인 가설 + 검증 절차 + 재발 방지 체크리스트', '너는 운영 회고 에이전트다.', 'incident-review', true, 0.15, 900, 60),
  ('*', 'webhook', true, '웹훅 설계/운영', '웹훅 이벤트 계약, 검증, 재시도, 운영 가드레일까지 포함한 실행안을 생성합니다.', '이벤트 종류, 공급자, 인증 방식, 처리 목표, 실패 정책', '엔드포인트 계약 + 검증/보안 + 재시도/멱등성 + 운영 체크리스트', '너는 웹훅 통합 아키텍트다.', 'webhook', false, 0.2, 1200, 70)
on conflict (guild_id, skill_id) do nothing;

create table if not exists public.agent_workflow_profiles (
  guild_id text not null default '*',
  priority text not null,
  enabled boolean not null default true,
  steps jsonb not null,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (guild_id, priority),
  check (priority in ('fast', 'balanced', 'precise')),
  check (jsonb_typeof(steps) = 'array')
);

create index if not exists idx_agent_workflow_profiles_enabled
  on public.agent_workflow_profiles (guild_id, enabled, updated_at desc);

drop trigger if exists trg_agent_workflow_profiles_updated_at on public.agent_workflow_profiles;
create trigger trg_agent_workflow_profiles_updated_at
before update on public.agent_workflow_profiles
for each row
execute function public.set_updated_at();

insert into public.agent_workflow_profiles (guild_id, priority, enabled, steps)
values
  ('*', 'fast', true, '[{"role":"planner","title":"목표 실행 계획 수립","skipWhenFast":true,"skipWhenRequestedSkill":false},{"role":"researcher","title":"실행안/근거 초안 작성","skipWhenFast":false,"skipWhenRequestedSkill":true},{"role":"critic","title":"리스크 검토 및 보완","skipWhenFast":true,"skipWhenRequestedSkill":true}]'::jsonb),
  ('*', 'balanced', true, '[{"role":"planner","title":"목표 실행 계획 수립","skipWhenFast":false,"skipWhenRequestedSkill":false},{"role":"researcher","title":"실행안/근거 초안 작성","skipWhenFast":false,"skipWhenRequestedSkill":true},{"role":"critic","title":"리스크 검토 및 보완","skipWhenFast":false,"skipWhenRequestedSkill":true}]'::jsonb),
  ('*', 'precise', true, '[{"role":"planner","title":"목표 실행 계획 수립","skipWhenFast":false,"skipWhenRequestedSkill":false},{"role":"researcher","title":"실행안/근거 초안 작성","skipWhenFast":false,"skipWhenRequestedSkill":true},{"role":"critic","title":"리스크 검토 및 보완","skipWhenFast":false,"skipWhenRequestedSkill":true}]'::jsonb)
on conflict (guild_id, priority) do nothing;

create table if not exists public.agent_privacy_policies (
  guild_id text primary key,
  enabled boolean not null default true,
  mode_default text not null default 'guarded',
  review_score integer not null default 60,
  block_score integer not null default 80,
  review_patterns jsonb not null default '[]'::jsonb,
  block_patterns jsonb not null default '[]'::jsonb,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (mode_default in ('direct', 'plan_act', 'deliberate', 'guarded')),
  check (review_score >= 0 and review_score <= 100),
  check (block_score >= 0 and block_score <= 100),
  check (block_score > review_score),
  check (jsonb_typeof(review_patterns) = 'array'),
  check (jsonb_typeof(block_patterns) = 'array')
);

create index if not exists idx_agent_privacy_policies_enabled
  on public.agent_privacy_policies (enabled, updated_at desc);

drop trigger if exists trg_agent_privacy_policies_updated_at on public.agent_privacy_policies;
create trigger trg_agent_privacy_policies_updated_at
before update on public.agent_privacy_policies
for each row
execute function public.set_updated_at();

insert into public.agent_privacy_policies (guild_id, enabled, mode_default, review_score, block_score, review_patterns, block_patterns)
values (
  '*',
  true,
  'guarded',
  60,
  80,
  '[
    {"pattern":"(이메일|전화번호|연락처|주소|주민등록|신분증|여권|계좌|카드번호|토큰|비밀키|api key)","score":28,"reason":"personal_or_secret_identifier"},
    {"pattern":"(실명|본명|생년월일|birthday|dob|학번|사번)","score":20,"reason":"identity_attribute"},
    {"pattern":"(환자|의료|진단|건강기록|병력|상담기록)","score":24,"reason":"health_sensitive_domain"},
    {"pattern":"(청소년|미성년|학생 개인정보|아동)","score":24,"reason":"minor_sensitive_context"}
  ]'::jsonb,
  '[
    {"pattern":"(원본.*(내보내|공유|전송)|전체.*덤프|raw.*log|대화 원문 전부)","score":55,"reason":"bulk_sensitive_export"},
    {"pattern":"(토큰.*보여|비밀키.*출력|패스워드.*공개|credentials?.*dump)","score":60,"reason":"secret_exposure_attempt"},
    {"pattern":"(개인정보.*수집.*자동|동의 없이|무단 수집)","score":50,"reason":"non_consensual_collection"}
  ]'::jsonb
)
on conflict (guild_id) do nothing;

create table if not exists public.agent_privacy_gate_samples (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  session_id text not null,
  mode text not null,
  decision text not null,
  expected_decision text,
  risk_score integer not null,
  reasons text[] not null default '{}',
  goal_hash text,
  goal_length integer,
  review_note text,
  reviewed_by text,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (mode in ('direct', 'plan_act', 'deliberate', 'guarded')),
  check (decision in ('allow', 'review', 'block')),
  check (expected_decision is null or expected_decision in ('allow', 'review', 'block')),
  check (risk_score >= 0 and risk_score <= 100),
  check (goal_length is null or goal_length >= 0)
);

create index if not exists idx_agent_privacy_gate_samples_guild_created
  on public.agent_privacy_gate_samples (guild_id, created_at desc);

create index if not exists idx_agent_privacy_gate_samples_review_queue
  on public.agent_privacy_gate_samples (guild_id, expected_decision, created_at desc);

drop trigger if exists trg_agent_privacy_gate_samples_updated_at on public.agent_privacy_gate_samples;
create trigger trg_agent_privacy_gate_samples_updated_at
before update on public.agent_privacy_gate_samples
for each row
execute function public.set_updated_at();

create table if not exists public.agent_tot_policies (
  guild_id text primary key,
  enabled boolean not null default true,
  strategy text not null default 'bfs',
  branch_angles jsonb,
  adaptive_sampling_enabled boolean not null default true,
  sampling_temp_min numeric(5, 4) not null default 0.1200,
  sampling_temp_max numeric(5, 4) not null default 0.4500,
  sampling_top_p_min numeric(5, 4) not null default 0.8200,
  sampling_top_p_max numeric(5, 4) not null default 0.9800,
  local_search_enabled boolean not null default true,
  local_search_mutations integer not null default 1,
  replay_enabled boolean not null default true,
  replay_top_k integer not null default 2,
  shadow_enabled boolean not null default false,
  max_branches integer not null default 3,
  keep_top integer not null default 1,
  active_enabled boolean not null default false,
  active_allow_fast boolean not null default false,
  active_min_goal_length integer not null default 60,
  active_min_score_gain integer not null default 4,
  active_min_beam_gain numeric(6, 4) not null default 0.0300,
  active_require_non_pass boolean not null default false,
  auto_tune_enabled boolean not null default true,
  auto_tune_interval_hours integer not null default 24,
  auto_tune_min_samples integer not null default 40,
  last_auto_tuned_at timestamptz,
  last_auto_tune_summary text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (strategy in ('bfs', 'dfs')),
  check (sampling_temp_min >= 0 and sampling_temp_min <= 1),
  check (sampling_temp_max >= 0 and sampling_temp_max <= 1),
  check (sampling_top_p_min >= 0 and sampling_top_p_min <= 1),
  check (sampling_top_p_max >= 0 and sampling_top_p_max <= 1),
  check (sampling_temp_min <= sampling_temp_max),
  check (sampling_top_p_min <= sampling_top_p_max),
  check (local_search_mutations >= 0 and local_search_mutations <= 3),
  check (replay_top_k >= 0 and replay_top_k <= 5),
  check (max_branches >= 2 and max_branches <= 6),
  check (keep_top >= 1 and keep_top <= 3),
  check (active_min_goal_length >= 20),
  check (active_min_score_gain >= 0 and active_min_score_gain <= 30),
  check (active_min_beam_gain >= 0 and active_min_beam_gain <= 1),
  check (auto_tune_interval_hours >= 1 and auto_tune_interval_hours <= 168),
  check (auto_tune_min_samples >= 10)
);

alter table public.agent_tot_policies add column if not exists active_min_beam_gain numeric(6, 4) not null default 0.0300;
alter table public.agent_tot_policies add column if not exists branch_angles jsonb;
alter table public.agent_tot_policies add column if not exists adaptive_sampling_enabled boolean not null default true;
alter table public.agent_tot_policies add column if not exists sampling_temp_min numeric(5, 4) not null default 0.1200;
alter table public.agent_tot_policies add column if not exists sampling_temp_max numeric(5, 4) not null default 0.4500;
alter table public.agent_tot_policies add column if not exists sampling_top_p_min numeric(5, 4) not null default 0.8200;
alter table public.agent_tot_policies add column if not exists sampling_top_p_max numeric(5, 4) not null default 0.9800;
alter table public.agent_tot_policies add column if not exists local_search_enabled boolean not null default true;
alter table public.agent_tot_policies add column if not exists local_search_mutations integer not null default 1;
alter table public.agent_tot_policies add column if not exists replay_enabled boolean not null default true;
alter table public.agent_tot_policies add column if not exists replay_top_k integer not null default 2;

create index if not exists idx_agent_tot_policies_enabled
  on public.agent_tot_policies (enabled, updated_at desc);

drop trigger if exists trg_agent_tot_policies_updated_at on public.agent_tot_policies;
create trigger trg_agent_tot_policies_updated_at
before update on public.agent_tot_policies
for each row
execute function public.set_updated_at();

insert into public.agent_tot_policies (
  guild_id,
  enabled,
  strategy,
  branch_angles,
  adaptive_sampling_enabled,
  sampling_temp_min,
  sampling_temp_max,
  sampling_top_p_min,
  sampling_top_p_max,
  local_search_enabled,
  local_search_mutations,
  replay_enabled,
  replay_top_k,
  shadow_enabled,
  max_branches,
  keep_top,
  active_enabled,
  active_allow_fast,
  active_min_goal_length,
  active_min_score_gain,
  active_min_beam_gain,
  active_require_non_pass,
  auto_tune_enabled,
  auto_tune_interval_hours,
  auto_tune_min_samples
) values ('*', true, 'bfs', null, true, 0.1200, 0.4500, 0.8200, 0.9800, true, 1, true, 2, false, 3, 1, false, false, 60, 4, 0.0300, false, true, 24, 40)
on conflict (guild_id) do nothing;

create table if not exists public.agent_tot_candidate_pairs (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  session_id text not null,
  strategy text not null,
  baseline_score integer not null,
  candidate_score integer not null,
  score_gain integer not null,
  beam_gain numeric(7, 4) not null default 0,
  promoted boolean not null default false,
  baseline_probability numeric(6, 4),
  baseline_probability_source text,
  baseline_correctness numeric(6, 4),
  baseline_beam_score numeric(6, 4),
  candidate_probability numeric(6, 4),
  candidate_probability_source text,
  candidate_correctness numeric(6, 4),
  candidate_beam_score numeric(6, 4),
  baseline_evidence_bundle_id text,
  candidate_evidence_bundle_id text,
  baseline_result text,
  candidate_result text,
  created_at timestamptz not null default now(),
  check (strategy in ('bfs', 'dfs')),
  check (baseline_score >= 0 and baseline_score <= 100),
  check (candidate_score >= 0 and candidate_score <= 100),
  check (score_gain >= -100 and score_gain <= 100),
  check (beam_gain >= -1 and beam_gain <= 1),
  check (baseline_probability is null or (baseline_probability >= 0 and baseline_probability <= 1)),
  check (baseline_probability_source is null or baseline_probability_source in ('provider_logprob', 'self_eval', 'fallback')),
  check (baseline_correctness is null or (baseline_correctness >= 0 and baseline_correctness <= 1)),
  check (baseline_beam_score is null or (baseline_beam_score >= 0 and baseline_beam_score <= 1)),
  check (candidate_probability is null or (candidate_probability >= 0 and candidate_probability <= 1)),
  check (candidate_probability_source is null or candidate_probability_source in ('provider_logprob', 'self_eval', 'fallback')),
  check (candidate_correctness is null or (candidate_correctness >= 0 and candidate_correctness <= 1)),
  check (candidate_beam_score is null or (candidate_beam_score >= 0 and candidate_beam_score <= 1))
);

alter table public.agent_tot_candidate_pairs add column if not exists beam_gain numeric(7, 4) not null default 0;
alter table public.agent_tot_candidate_pairs add column if not exists baseline_probability numeric(6, 4);
alter table public.agent_tot_candidate_pairs add column if not exists baseline_probability_source text;
alter table public.agent_tot_candidate_pairs add column if not exists baseline_correctness numeric(6, 4);
alter table public.agent_tot_candidate_pairs add column if not exists baseline_beam_score numeric(6, 4);
alter table public.agent_tot_candidate_pairs add column if not exists candidate_probability numeric(6, 4);
alter table public.agent_tot_candidate_pairs add column if not exists candidate_probability_source text;
alter table public.agent_tot_candidate_pairs add column if not exists candidate_correctness numeric(6, 4);
alter table public.agent_tot_candidate_pairs add column if not exists candidate_beam_score numeric(6, 4);

create index if not exists idx_agent_tot_candidate_pairs_guild_created
  on public.agent_tot_candidate_pairs (guild_id, created_at desc);

create index if not exists idx_agent_tot_candidate_pairs_guild_promoted
  on public.agent_tot_candidate_pairs (guild_id, promoted, created_at desc);

alter table public.agent_runtime_policies enable row level security;
alter table public.agent_skill_catalog enable row level security;
alter table public.agent_workflow_profiles enable row level security;
alter table public.agent_privacy_policies enable row level security;
alter table public.agent_privacy_gate_samples enable row level security;
alter table public.agent_tot_policies enable row level security;
alter table public.agent_tot_candidate_pairs enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='agent_runtime_policies' and policyname='agent_runtime_policies_guild_all'
  ) then
    create policy agent_runtime_policies_guild_all on public.agent_runtime_policies
      for all
      using (auth.role() = 'service_role' or guild_id in (coalesce(auth.jwt() ->> 'guild_id', ''), '*'))
      with check (auth.role() = 'service_role' or guild_id in (coalesce(auth.jwt() ->> 'guild_id', ''), '*'));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='agent_skill_catalog' and policyname='agent_skill_catalog_guild_all'
  ) then
    create policy agent_skill_catalog_guild_all on public.agent_skill_catalog
      for all
      using (auth.role() = 'service_role' or guild_id in (coalesce(auth.jwt() ->> 'guild_id', ''), '*'))
      with check (auth.role() = 'service_role' or guild_id in (coalesce(auth.jwt() ->> 'guild_id', ''), '*'));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='agent_workflow_profiles' and policyname='agent_workflow_profiles_guild_all'
  ) then
    create policy agent_workflow_profiles_guild_all on public.agent_workflow_profiles
      for all
      using (auth.role() = 'service_role' or guild_id in (coalesce(auth.jwt() ->> 'guild_id', ''), '*'))
      with check (auth.role() = 'service_role' or guild_id in (coalesce(auth.jwt() ->> 'guild_id', ''), '*'));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='agent_privacy_policies' and policyname='agent_privacy_policies_guild_all'
  ) then
    create policy agent_privacy_policies_guild_all on public.agent_privacy_policies
      for all
      using (auth.role() = 'service_role' or guild_id in (coalesce(auth.jwt() ->> 'guild_id', ''), '*'))
      with check (auth.role() = 'service_role' or guild_id in (coalesce(auth.jwt() ->> 'guild_id', ''), '*'));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='agent_privacy_gate_samples' and policyname='agent_privacy_gate_samples_guild_all'
  ) then
    create policy agent_privacy_gate_samples_guild_all on public.agent_privacy_gate_samples
      for all
      using (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''))
      with check (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='agent_tot_policies' and policyname='agent_tot_policies_guild_all'
  ) then
    create policy agent_tot_policies_guild_all on public.agent_tot_policies
      for all
      using (auth.role() = 'service_role' or guild_id in (coalesce(auth.jwt() ->> 'guild_id', ''), '*'))
      with check (auth.role() = 'service_role' or guild_id in (coalesce(auth.jwt() ->> 'guild_id', ''), '*'));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='agent_tot_candidate_pairs' and policyname='agent_tot_candidate_pairs_guild_all'
  ) then
    create policy agent_tot_candidate_pairs_guild_all on public.agent_tot_candidate_pairs
      for all
      using (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''))
      with check (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;
end
$$;

-- ==========================================
-- 18. Retrieval eval / shadow / auto-tuning
-- ==========================================

create table if not exists public.retrieval_eval_sets (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  name text not null,
  description text,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (guild_id, name)
);

create index if not exists idx_retrieval_eval_sets_guild_updated
  on public.retrieval_eval_sets (guild_id, updated_at desc);

drop trigger if exists trg_retrieval_eval_sets_updated_at on public.retrieval_eval_sets;
create trigger trg_retrieval_eval_sets_updated_at
before update on public.retrieval_eval_sets
for each row
execute function public.set_updated_at();

create table if not exists public.retrieval_eval_cases (
  id bigint generated by default as identity primary key,
  eval_set_id bigint not null references public.retrieval_eval_sets(id) on delete cascade,
  guild_id text not null,
  query text not null,
  intent text,
  difficulty text not null default 'normal',
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (difficulty in ('easy', 'normal', 'hard'))
);

create index if not exists idx_retrieval_eval_cases_set_updated
  on public.retrieval_eval_cases (eval_set_id, updated_at desc);

create index if not exists idx_retrieval_eval_cases_guild_enabled
  on public.retrieval_eval_cases (guild_id, enabled, updated_at desc);

drop trigger if exists trg_retrieval_eval_cases_updated_at on public.retrieval_eval_cases;
create trigger trg_retrieval_eval_cases_updated_at
before update on public.retrieval_eval_cases
for each row
execute function public.set_updated_at();

create table if not exists public.retrieval_eval_targets (
  id bigint generated by default as identity primary key,
  case_id bigint not null references public.retrieval_eval_cases(id) on delete cascade,
  target_file_path text not null,
  gain numeric(5, 2) not null default 1,
  created_at timestamptz not null default now(),
  unique (case_id, target_file_path),
  check (gain > 0)
);

create index if not exists idx_retrieval_eval_targets_case
  on public.retrieval_eval_targets (case_id, gain desc);

create table if not exists public.retrieval_eval_runs (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  eval_set_id bigint references public.retrieval_eval_sets(id) on delete set null,
  requested_by text,
  status text not null default 'running',
  top_k integer not null default 5,
  variants text[] not null default '{baseline}',
  case_count integer not null default 0,
  result_count integer not null default 0,
  summary jsonb,
  error text,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (status in ('running', 'completed', 'failed', 'canceled')),
  check (top_k >= 1 and top_k <= 50)
);

create index if not exists idx_retrieval_eval_runs_guild_created
  on public.retrieval_eval_runs (guild_id, created_at desc);

create index if not exists idx_retrieval_eval_runs_status_started
  on public.retrieval_eval_runs (status, started_at desc);

drop trigger if exists trg_retrieval_eval_runs_updated_at on public.retrieval_eval_runs;
create trigger trg_retrieval_eval_runs_updated_at
before update on public.retrieval_eval_runs
for each row
execute function public.set_updated_at();

create table if not exists public.retrieval_eval_results (
  id bigint generated by default as identity primary key,
  run_id bigint not null references public.retrieval_eval_runs(id) on delete cascade,
  guild_id text not null,
  case_id bigint not null references public.retrieval_eval_cases(id) on delete cascade,
  variant text not null,
  query text not null,
  executed_query text,
  top_k integer not null,
  recall_at_k numeric(6, 4) not null,
  mrr numeric(6, 4) not null,
  ndcg numeric(6, 4) not null,
  hit_at_k integer not null,
  latency_ms integer not null,
  retrieved_paths jsonb not null default '[]'::jsonb,
  expected_paths jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  check (top_k >= 1 and top_k <= 50),
  check (recall_at_k >= 0 and recall_at_k <= 1),
  check (mrr >= 0 and mrr <= 1),
  check (ndcg >= 0 and ndcg <= 1),
  check (hit_at_k in (0, 1)),
  check (latency_ms >= 0)
);

create index if not exists idx_retrieval_eval_results_run_variant
  on public.retrieval_eval_results (run_id, variant, created_at asc);

create index if not exists idx_retrieval_eval_results_case
  on public.retrieval_eval_results (case_id, created_at desc);

create table if not exists public.retrieval_ranker_experiments (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  run_id bigint references public.retrieval_eval_runs(id) on delete set null,
  requested_by text,
  baseline_variant text not null default 'baseline',
  candidate_variant text not null,
  baseline_ndcg numeric(6, 4) not null,
  candidate_ndcg numeric(6, 4) not null,
  ndcg_delta numeric(6, 4) not null,
  baseline_latency_ms numeric(10, 2),
  candidate_latency_ms numeric(10, 2),
  latency_delta_ms numeric(10, 2),
  decision text not null default 'recommended',
  meta jsonb,
  created_at timestamptz not null default now(),
  check (decision in ('recommended', 'applied', 'rejected'))
);

create index if not exists idx_retrieval_ranker_experiments_guild_created
  on public.retrieval_ranker_experiments (guild_id, created_at desc);

create table if not exists public.retrieval_ranker_active_profiles (
  guild_id text primary key,
  active_variant text not null default 'baseline',
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_retrieval_ranker_active_profiles_updated_at on public.retrieval_ranker_active_profiles;
create trigger trg_retrieval_ranker_active_profiles_updated_at
before update on public.retrieval_ranker_active_profiles
for each row
execute function public.set_updated_at();

alter table public.retrieval_eval_sets enable row level security;
alter table public.retrieval_eval_cases enable row level security;
alter table public.retrieval_eval_targets enable row level security;
alter table public.retrieval_eval_runs enable row level security;
alter table public.retrieval_eval_results enable row level security;
alter table public.retrieval_ranker_experiments enable row level security;
alter table public.retrieval_ranker_active_profiles enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='retrieval_eval_sets' and policyname='retrieval_eval_sets_guild_all'
  ) then
    create policy retrieval_eval_sets_guild_all on public.retrieval_eval_sets
      for all
      using (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''))
      with check (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='retrieval_eval_cases' and policyname='retrieval_eval_cases_guild_all'
  ) then
    create policy retrieval_eval_cases_guild_all on public.retrieval_eval_cases
      for all
      using (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''))
      with check (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='retrieval_eval_targets' and policyname='retrieval_eval_targets_all'
  ) then
    create policy retrieval_eval_targets_all on public.retrieval_eval_targets
      for all
      using (
        auth.role() = 'service_role'
        or exists (
          select 1
          from public.retrieval_eval_cases c
          where c.id = retrieval_eval_targets.case_id
            and c.guild_id = coalesce(auth.jwt() ->> 'guild_id', '')
        )
      )
      with check (
        auth.role() = 'service_role'
        or exists (
          select 1
          from public.retrieval_eval_cases c
          where c.id = retrieval_eval_targets.case_id
            and c.guild_id = coalesce(auth.jwt() ->> 'guild_id', '')
        )
      );
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='retrieval_eval_runs' and policyname='retrieval_eval_runs_guild_all'
  ) then
    create policy retrieval_eval_runs_guild_all on public.retrieval_eval_runs
      for all
      using (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''))
      with check (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='retrieval_eval_results' and policyname='retrieval_eval_results_guild_all'
  ) then
    create policy retrieval_eval_results_guild_all on public.retrieval_eval_results
      for all
      using (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''))
      with check (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='retrieval_ranker_experiments' and policyname='retrieval_ranker_experiments_guild_all'
  ) then
    create policy retrieval_ranker_experiments_guild_all on public.retrieval_ranker_experiments
      for all
      using (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''))
      with check (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='retrieval_ranker_active_profiles' and policyname='retrieval_ranker_active_profiles_guild_all'
  ) then
    create policy retrieval_ranker_active_profiles_guild_all on public.retrieval_ranker_active_profiles
      for all
      using (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''))
      with check (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;
end
$$;

-- ==========================================
-- 17. Dynamic worker approvals persistence
-- ==========================================

create table if not exists public.worker_approvals (
  id text primary key,
  guild_id text not null,
  requested_by text not null,
  goal text not null,
  action_name text not null,
  generated_code text not null,
  sandbox_dir text,
  sandbox_file_path text,
  validation_passed boolean not null default false,
  validation_errors text[] not null default '{}',
  validation_warnings text[] not null default '{}',
  admin_message_id text,
  admin_channel_id text,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (status in ('pending', 'approved', 'rejected', 'refactor_requested'))
);

create index if not exists idx_worker_approvals_status_updated
  on public.worker_approvals (status, updated_at desc);

create index if not exists idx_worker_approvals_guild_created
  on public.worker_approvals (guild_id, created_at desc);

drop trigger if exists trg_worker_approvals_updated_at on public.worker_approvals;
create trigger trg_worker_approvals_updated_at
before update on public.worker_approvals
for each row
execute function public.set_updated_at();

alter table public.worker_approvals enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='worker_approvals' and policyname='worker_approvals_guild_all'
  ) then
    create policy worker_approvals_guild_all on public.worker_approvals
      for all
      using (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''))
      with check (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;
end
$$;

drop trigger if exists trg_memory_jobs_updated_at on public.memory_jobs;
create trigger trg_memory_jobs_updated_at
before update on public.memory_jobs
for each row
execute function public.set_updated_at();

-- ==========================================
-- 16. Tenant action governance
-- ==========================================

create table if not exists public.agent_action_policies (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  action_name text not null,
  enabled boolean not null default true,
  run_mode text not null default 'auto',
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (guild_id, action_name),
  check (run_mode in ('auto', 'approval_required', 'disabled'))
);

create index if not exists idx_agent_action_policies_guild_action
  on public.agent_action_policies (guild_id, action_name);

drop trigger if exists trg_agent_action_policies_updated_at on public.agent_action_policies;
create trigger trg_agent_action_policies_updated_at
before update on public.agent_action_policies
for each row
execute function public.set_updated_at();

create table if not exists public.agent_action_approval_requests (
  id text primary key,
  guild_id text not null,
  requested_by text not null,
  goal text not null,
  action_name text not null,
  action_args jsonb not null default '{}'::jsonb,
  status text not null default 'pending',
  reason text,
  approved_by text,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  check (status in ('pending', 'approved', 'rejected', 'expired'))
);

create index if not exists idx_agent_action_approvals_guild_created
  on public.agent_action_approval_requests (guild_id, created_at desc);

create index if not exists idx_agent_action_approvals_status_expires
  on public.agent_action_approval_requests (status, expires_at asc);

alter table public.agent_action_policies enable row level security;
alter table public.agent_action_approval_requests enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='agent_action_policies' and policyname='agent_action_policies_guild_all'
  ) then
    create policy agent_action_policies_guild_all on public.agent_action_policies
      for all
      using (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''))
      with check (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='agent_action_approval_requests' and policyname='agent_action_approvals_guild_all'
  ) then
    create policy agent_action_approvals_guild_all on public.agent_action_approval_requests
      for all
      using (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''))
      with check (auth.role() = 'service_role' or guild_id = coalesce(auth.jwt() ->> 'guild_id', ''));
  end if;
end
$$;
